### ISSUE TITLE
باگ پیام ورود به سرور

### ISSUE THREAD

**Issue by hamed0mh** [wizwizdev/wizwizxui-timebot#10]
زمانی که یه اکانت میسازی همینجوری پشت هم پیام ورود موفقیت آمیز سرور میاد

**Comment by wizwizdev** [comment]
دیتابیس برای ربات باید جدید باشه
توکن باید جدید باشه ( از قبل اگه استفاده کردین امکانش نیست )
و طبق مراحل نصب پیش برید مشکلی پیش نمیاد
