### ISSUE TITLE
 باگ پنل چینی اطلاعات اکانت

### ISSUE THREAD

**Issue by Masood43** [wizwizdev/wizwizxui-timebot#100]
سلام من پنل چینی دارم ربات اون اکانت های که تاریخ نداره رو اطلاعات کانفیگ میده ولی اون اکانت های که تاریخ داره رو اطلاعات کانفیگ شون رو نمی‌ده هم روی سررو تست گرفتم هم روی هاست چندین بار تست کردم برای دوستانم هم که از پنل چینی استفاده میکنن این مشکل رو داره

**Comment by wizwizdev** [comment]
سلام قسمت مشخصات کانفیک؟ یا قسمت کانفیگ های من؟

**Comment by Masood43** [comment]
سلام قسمت مشخصات کانفیگ

**Comment by Masood43** [comment]
چکاری باید انجام بدیم حالا
