### ISSUE TITLE
مشکل نمایش کانفیگ های من

### ISSUE THREAD

**Issue by mobohes** [wizwizdev/wizwizxui-timebot#1019]
1. مشکل نمایش لینک سابسکریپشن تو بخش (کانفیگ های من )که خالی نشان میدهد همچنین اگر داخل ربات دو بخش ولوم وب و لینک ساب روشن باشه،  یا هیچ کدومو نشون نمیده یا یکیشون که بهتره چنانچه جفتش روشنه هر دو را نشان بده یا حداقل بخشی را خالی نفرسته
![Screenshot 2024-05-23 230048](https://github.com/wizwizdev/wizwizxui-timebot/assets/138327918/2b8b7788-e5b6-4086-8e05-47e8294a4525)

**Comment by wizwizdev** [comment]
خالی نمیفرسته شما توی تنظیمات خاموش کردی

**Comment by wizwizdev** [comment]
بعدشم عزیز اشتراکی باید پیوی پشتیبانی بگی نه گیت

**Comment by mobohes** [comment]
> خالی نمیفرسته شما توی تنظیمات خاموش کردی

روشن بوده گزینش موقع پرداخت فقط نشونش میده
