### ISSUE TITLE
نمایش کانفیگ های آماده 

### ISSUE THREAD

**Issue by mobohes** [wizwizdev/wizwizxui-timebot#1020]
در ربات کانفیگ های آماده به شکل خوبی به کاربر نشان داده نمیشود و تشخیص کانفیگ برای مشتری سخته

چند تا پیشنهاد دارم:
به جای نمایش کانفیگ به عنوان اسم ، نام دسته بندی در کنار نام پلن نشان داده شود
یا ریمارک کانفیگ تهیه شده به کاربر نشان داده شود
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/138327918/cb260bb4-bbfa-486a-ba95-f5cd1d3360c2)

**Comment by wizwizdev** [comment]
کانفیگ کلا با اسم نمایش میده اینی ک شما دارین باک از طرف خود شماست

**Comment by mobohes** [comment]
اشتباه از من بود این قسمت که من مورد داشتم برای نسخه پولی بات بود عذر میخوام
