### ISSUE TITLE
Warnusers.php

### ISSUE THREAD

**Issue by nexus-service** [wizwizdev/wizwizxui-timebot#1032]
سلام خسته نباشید، 
اول کلی ممنون بابت بات.
دوم اینکه فکر نکنم فایل Warnusers برای مرزبان آپدیت شده باشه ، ممنون میشم آپدیت کنید ؛ هرچقدر تلاش کردم خودم انجام بدم به جایی نرسیدم . 
مرسی کلی

**Comment by wizwizdev** [comment]
سلام حتما

**Comment by nexus-service** [comment]
ممنون
