### ISSUE TITLE
مشکل در والیوم‌وب در نسخه جدید براب مرزبان

### ISSUE THREAD

**Issue by amirhr098** [wizwizdev/wizwizxui-timebot#1044]
سلام. من آپدیت کردم ربات و پنل رو ولی والیوم‌وب این ارور رو میده برای کانفیگ‌های مرزبان.
![Screenshot_20240530_014051_Chrome](https://github.com/wizwizdev/wizwizxui-timebot/assets/95343201/b31287e5-2e54-42d0-89e8-a0fa472d1256)

**Comment by wizwizdev** [comment]
سلام ولیوم وب ببرای مرزبان وجود نداره
