### ISSUE TITLE
نحوه ساخت اکانت تست در پنل مرزبان

### ISSUE THREAD

**Issue by rbsdotnet** [wizwizdev/wizwizxui-timebot#1049]
درود
نحوه ساخت اکانت تست در پنل مرزبان به چه صورت هست؟ 
سپاس از شما

**Comment by wizwizdev** [comment]
سلام قیمت 0

**Comment by rbsdotnet** [comment]
> سلام قیمت 0

درود وقتی قیمت رو صفر میزارم نمایش نمیده

**Comment by rbsdotnet** [comment]
> سلام قیمت 0

سپاس

**Comment by RezaNaghideh** [comment]
> rbsdotnet

سلام در صورت تمایل با ایمیل rezanzg@gmail.com 
با من در ارتباط باشین برای پیاده سازی پنل  هیدیفای.
پیام رو اونحا پاک کردن
