### ISSUE TITLE
نحوه تغییر نمایش کلیدها

### ISSUE THREAD

**Issue by rbsdotnet** [wizwizdev/wizwizxui-timebot#1050]
درود امکانش هست جای کلیدها مثل کلید برگشت سمت کیبورد ها باشه؟
اوقتی داخل پیام ها هست یکم برای کاربر گیج کننده هست

و مورد بعدی اینکه دسته ای که داخلش اکانت تست هست رو چه جوری میشه داخل فروش نیاره  
مثلا یک روزه 1 گیگ با قیمت صفر

**Comment by wizwizdev** [comment]
سلام مورد اول نیاز ب دانش برنامه نویسی داره
مورد دوم هم خب ی دسته جدید برای تست بزن ک توی فروش نیاد انقدر سخته xd
