### ISSUE TITLE
مشکل در بروزرسانی لینک کانفیگ

### ISSUE THREAD

**Issue by NaderKochike** [wizwizdev/wizwizxui-timebot#1056]
من توی ویز ویز دوتا سرور ادد کردم یکیش برا همراه اول یکی هم برای ایرانسل
مشتری کانفیگ ایرانسل میخره
بعد کانفیگ رو گم میکنه مثلا
میاد تو بخش کانفیگای من و رو کانفیگش میزنه و بروزرسانی لینک رو میزنه
ولی از سرور همراه اول براش لینک کانفیگو میده(آدرس رو اشتباه میزنه)
این رو کجا باید درست کرد

**Comment by wizwizdev** [comment]
سلام توی کانال این اموزش هست به صورت ویدیو
