### ISSUE TITLE
کیف پول

### ISSUE THREAD

**Issue by rbsdotnet** [wizwizdev/wizwizxui-timebot#1058]
درود وقت بخیر
یه سوال داشتم وقتی حساب کیف پول شارژ میشه سند اینکه شارژ شده در کدام بخش هست
منظورم این هست وقتی چندبار شارژ میشه این اطلاعات کجا ذخیره میشه؟
تاریخ X مبلغ A تومان
تاریخ W مبلغ B  تومان
از چه طریقی میشه تعداد واریزی کیف پول رو بدست آورد؟

**Comment by wizwizdev** [comment]
سلام توی دیتابیس pays

**Comment by rbsdotnet** [comment]
> سلام توی دیتابیس pays

برای حالت افزایش موجودی یه صورت دستی اطلاعاتی ذخیره نمیشه
در منوی مدیریت افزایش موجودی ایدی کاربر سپس مبلغ رو که وارد میکنم اطلاعاتی در جدول pays ذخیره نمیشه
