### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by Artinxrz** [wizwizdev/wizwizxui-timebot#106]
اگه میشه ی چیز اضافه کنید به بات سرور تستی بدیم مشتری هامون وقتی ی بار اومد تست. زد دیگ تست نتونه بزنه

**Comment by arian2240** [comment]
> اگه میشه ی چیز اضافه کنید به بات سرور تستی بدیم مشتری هامون وقتی ی بار اومد تست. زد دیگ تست نتونه بزنه

همین الانشم هست کافیه موقع ساخت پلن قیمتشو 0 بزنی

**Comment by wizwizdev** [comment]
شما ادمینی برای ادمین کلا رایگان

**Comment by HamidRouter** [comment]
وقت بخیر،
با احترام به دولوپر عزیز، 
تصمیم گرفتم توضیحات رو کامل کنم در این مواقع بهتره که دستی ایجاد کنید(و این مشکل نیست که قابل حل باشد)
مدیریت ربات-ساخت اکانت-سرور ها را انتخاب کنید پلن تست را انتخاب کنید روز دلخواه ، مقدار حجم هم از 200 مگابایت تا هر چقدر میتونید وارد کنید
برای 200 مگابایت به صورت زیر وارد میکنید،
0.2
