### ISSUE TITLE
حجم اکانت تست

### ISSUE THREAD

**Issue by NaderKochike** [wizwizdev/wizwizxui-timebot#1061]
سلام
من چرا نمیتونم مثل قبل حجم اکانت تستم رو یه عدد اعشاری بزنم
میگه حتما باید عدد حسابی باشه
![IMG_20240607_141613](https://github.com/wizwizdev/wizwizxui-timebot/assets/170880110/db11a205-eb11-4ec7-8c1a-6da25ecac4c1)

**Comment by wizwizdev** [comment]
سلام توی ربات اینکارو بکنید ، پنل بعدا حل میشه
