### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by Mohammadsdq** [wizwizdev/wizwizxui-timebot#1069]
چرا وقتی دارم نصب میکنم خیلی طول میکشه و یهو قطع مشه وسط نصب کردن ؟

**Comment by Mahbelit** [comment]
سرورت عوض کن.
 سخت افزارت قدیمی هست یا اورسل خالصی.

**Comment by Mohammadsdq** [comment]
اره درست شد ممنون
