### ISSUE TITLE
عدم ارسال پیام ربات

### ISSUE THREAD

**Issue by chav0sh** [wizwizdev/wizwizxui-timebot#1091]
سلام

روی سرور با لوکیشن هلند، سرتیفیکیت گرفتم بعدش اول پنل سنایی رو نصب کردم و بعدش wizwiz

بعد از اینکه wizwiz نصب شد خود ربات پیام داد که با موفقیت نصب شده اما بعدش هرچی استارت میزنم جوابی نمیده
پنل sql و wizwiz بدون مشکل بالا میاد

از تونل پنل به پنل با استفاده از reverse استفاده میکنم نمیدونم تاثیری روی این موضوع داره یا نه

**Comment by wizwizdev** [comment]
سلام ویزویز و سنایی کنار هم نباید باشه و جدا باید نصب بشن
