### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by Armingbz** [wizwizdev/wizwizxui-timebot#113]
سلام و خسته نباشيد نميدونم چرا رباتم هنگ پيدا كرده روي مديريت سرور ميزنم حيچي نمياره

**Comment by HamidRouter** [comment]
وقت بخیر،
مشکل پیش آمده مربوط به هاست شماست روی سرور نصب کردین یا Cpanel

**Comment by Armingbz** [comment]
سرور هتزنر

**Comment by HamidRouter** [comment]
> سرور هتزنر
----------------
پیشنهادم به شما اینه یکبار سرور رو sudo reboot بزنید مجدد تست کنید اگر نشد بفرمایید راه کار بعدی رو خدمتتون بگم

**Comment by Armingbz** [comment]
ممنون از شما
sudo reboot
اينو بزنم اطلاعات ربات حذف نشه؟

**Comment by HamidRouter** [comment]
نه با خیال راحت انجام بدین چیزی حذف نمیشه

> ممنون از شما sudo reboot اينو بزنم اطلاعات ربات حذف نشه؟

**Comment by Armingbz** [comment]
متاسفانه اينو زدم خاموش روشن شد ولي باز روي مديريت سرور ميزنم حيچي نمياره

**Comment by HamidRouter** [comment]
> متاسفانه اينو زدم خاموش روشن شد ولي باز روي مديريت سرور ميزنم حيچي نمياره

آی دی تلگرامتون رو بذارید پیام بدم خدمتتون

**Comment by Armingbz** [comment]
چشم ممنون از شما كه كمك ميكنيد

@armingbz

**Comment by Armingbz** [comment]
مشكلم حل شد ممنون از پيگيريتون
