### ISSUE TITLE
اشکال در پرداخت با ترون

### ISSUE THREAD

**Issue by 4ydeen** [wizwizdev/wizwizxui-timebot#1134]
در نسخه یکی مونده به اخر که قیمت ترون رو‌‌ کمتر میزد ولی در نسخه اخر که گفته شد مشکل حل شده بعد از وارد کردن مبلغ به تومان ربات قفل میکنه و پیامی نمیاد دیگه. یعنی تو تبدیل تومان به ترون روی منتظر بمانید میمونه

**Comment by wizwizdev** [comment]
از خیلی چیزا میتونه باشه اینطوری چیزی نمیشه گف

**Comment by DholeDog** [comment]
مشکل منم همینه درگاه ترون کلا کار نمیکنه میگه منتظر بمانید و قفل میشه اگر میشه یک بررسی بکنید
