### ISSUE TITLE
پیشنهاد برای اشتراکی 

### ISSUE THREAD

**Issue by wizwizdev** [wizwizdev/wizwizxui-timebot#1159]
سلام دوستان لطفا پیشنهاد خودتون رو بنویسید و از بقیه عزیزان خواهشمندم اگر پیشنهاد دوستان توجه شمارو جلب کرد حتما ری اکشن بزارید و هرکدوم ری اکشن بالا داشته باشه و توجه منو جلب کنه توی آپدیت میارم ، همگی عشقمید ❤️

**Comment by Mhwdiy** [comment]
لطفا یه گزینه بزارین که بشه انتخاب دیوایس رو غیرفعال کرد

**Comment by MaMMaD1999** [comment]
بسته های حجمی و زمانی هم قابلیت اینو داشته باشن رو بعضی سرور ها فعال باشن رو بعضی نه

مثلا یه سرور نامحدود، بسته زمانی اضافه روش باید فروخت 
و یه سرورم که حجمیه، بسته حجمی

وقتی جفتش همزمان فعال کنی، توی جفت سرور ها فعال میشه و یجورایی انگاری قیمت ها قاطی میشن

**Comment by hosseini2024** [comment]
پروتکل وایرگارد لطفا اضافه کنید 

برای بخش زبر مجموعه گیری پورسانت به صورت درصد قابل تنظیم باشه

**Comment by Yusef13640628** [comment]
سلام کارتون بسیار عالیه

**Comment by iamfarhad** [comment]
سلام
یه مشکلی که وجود داره ایجاد پلن برای سرور هاست
اگر هر سرور ۲۰ تا پلن داشته باشه ادم نمیتونه کل سرور هارو اپدیت کنه
اگر امکانی باشه که پلن ها مشترک باشه و بشه گروهی توی نسخه وب قیمت هارو ویرایش کرد خیلی خوب میشه

**Comment by MaMMaD1999** [comment]
پلن دلخواهی که مشتری میسازه بتونه همونو تمید کنه و همون بمونه، مثلا پلن پایه 30 گیگ و 50 گیگ یک ماهه هست، کاربر میاد 40 گیگ 40 روزه دلخواه میگیره، اما موقع تمدید مجبوره همون پلن پایه ای که فعال کرده تمدید شه و نمیتونه همون 40 گیگ و 40 روزی که میخواسته رو تمدید کنه و مجبوره سرویس جدید بخره برای این کار و این خیلی بد و غیر حرفیه ایه!

کلا اگه پلن دلخواه نیاز به پلن پایه نداشته باشه و هرچی کاربر خودش ساخت برای خودش بمونه و بتونه همونو تمدید کنه خیلی خوب میشه👍

**Comment by saeedk1989** [comment]
نامگذاری پلن دلخواه اگه ترتیب خاصی نداشته باشه خیلی بهتره ترکیبی از حروف، کرکتر و عدد باشه!

**Comment by MaMMaD1999** [comment]
پنل x-ui با اسم کانفیگ های فارسی مشکلی نداره، ربات هم من یه کانفیگ با اسم فارسی توی پنل ساختم و بعد دستی به کانفیگ های من اضافه اش کردم باگ نخورد و اوکی بود، اگه کلا محدودیت نحوه ی اسم گزاری برداشته بشه هم بهتره

**Comment by farzamw** [comment]
یه گزینه ای باشه که با فعال کردنش بعد از ارسال کانفیگ به مشتری ، خودکار لینک زیر مجموعه گیری و توضیحاتش برای مشتری ارسال شده تا ترغیب شه به انجام این کار

**Comment by mahdaviniaali** [comment]
الان نماینده ها رو تمدید ها پورسانت واسشون نمیاد و این خیلی اذیت میکنه ممنون میشم درستشون کنید

و اگه میشه یه کاری کنیم که نماینده ها بتونن به صورت هفتگی یا ماهیانه بدهی رو پرداخت بزنن
سقف بدهی هم داشته باشه
و در صورت پرداخت نکردن به ما یگه که پرداخت نشده تو مرحله اول غیر فغال و بعدش پاک بشه

**Comment by lostsoul6** [comment]
درود وقت بخیر . قابلیتی بزارید که وقتی یک اینباند در x-ui به یک اینباند دیگر فالبک میشود ، لینکی که ربات میدهد صحیح باشد . در حال حاضر وقتی یک اینباند فالبک میشود روی اینباند دیگر ، لینکی که ربات تولید میکند صحیح نیست . باید قابلیتی باشد که اگر اینباند فالبک بود ، بتوان از طریق سایت برخی از پارامترها را overwrite کرد . پارامترهایی مانند port و path و sni و سایر موارد مورد نیاز به طوری که لینک نهایی که کاربر تحویل میگیرد صحیح باشد .

**Comment by Sepanta7** [comment]
کاش این گزینه ها هم باشن

1.گزینه اضافه کردن دکمه معمولی (منظور از معمولی شیشه ای نیست)

2.گزینه محروم کردن کاربران از گروپنه شانس

3یک راه حل باشه که نتونن کارت رو مسدود کنن

**Comment by mmdkevin** [comment]
سلام و خسته نباشید این **گزینه دیوایس هارو به نظرم جای مناسبی نمایش نمیده** ، باید بعد از اینکه مشتری خریدش انجام شد نمایش بده
یه جایی که نیان هر روز این سوال رو بپرسن:
![image](https://github.com/user-attachments/assets/ceebe2a3-b67e-4aca-a442-5e3f22a38854)

**Comment by mmdkevin** [comment]
یه مورد اصلاحی هست امیدوارم خوب توضیح بدم :
تو قسمت **کانفیگ های من** اصولا مثل **حجم باقی مانده** باید اطلاعات رو از تو پنل بخونه به مشتری **درست** نمایش بده ولی مثل اینکه (طبق گفته پشتیبانی خودتون) وقتی مشتری خرید میزنه و بعد یک بار تمدید میزنه تاریخ انقضا رو میاد اضافه میکنه به تاریخ قبلی ، یعنی شما فرض کن مشتری حجمش زود تر تموم شده اومده امروز تمدید زده ولی ربات میاد ( به صورت نمایشی) زمان رو اضافه میکنه و نمایش میده در حالی که اصلا اینطوری نیست - نباید اضافه کنه باید چیزی که تو x-ui هست و درسته رو نمایش بده
اصولا تمدید میزنیم اضافه نمیشه که همه چی ریست میشه و باید از تو x-ui بخونه نمایش بده 
![image](https://github.com/user-attachments/assets/0c65587d-89e7-489e-bc0a-1c564ad1a070)
![image](https://github.com/user-attachments/assets/0f665764-d352-493a-97c6-1aab6d7cc7fe)

**Comment by mmdkevin** [comment]
من یه تصویر ضمیمه این پیشنهاد کردم که چندین قابلیت داخل این تصویر هست ، به ترتیب شماره گذاری توضیحشون میدم:
1- وقتی چندین دقیقه بعد از دریافت اکانت تست حجمی استفاده نشه و کلا **کانکشن صورت نگیره** ربات یه پیام مثل تصویر بده  که متن و ... هم قابلیت شخصی سازی داشته باشه
2- وقتی روی دکمه وصل نشدم میزنی اون پیام نشون داده میشه 
3- وقتی روی دکمه وصل شدم میزنی اون پیام نشون داده میشه و قابلیت امتیاز دهی هم داره ، و اینکه چطوری امتیاز مشتری رو بعدا به ما نشون بده این بستگی به سلیقه ویزویز عزیز داره که اون سمت رو چطوری پیاده سازی کنه ، میتونه ربات همون لحظه مثل تیکت ها امتیازی که مشتری داده رو نشون ما بده یا اصلا میتونه جایی که ربات پیام داده فلانی اکانت تست رو گرفته پیام ادیت بشه و امتیاز نشون داده بشه یا اینکه تو قسمتی که کانفیگ های کاربر رو میشه دید اونجا نمایش بده
![3](https://github.com/user-attachments/assets/bc6cb87a-5429-471a-80d0-434dedb83ed3)

**Comment by mmdkevin** [comment]
**همه ما یک سری قوانین داریم مثل :**
مشتری رسید ارسال کرده و داخل توضیحات زده **برای خرید VPN**
بهتره مثل تصویر زیر در **اولین مرحله** یعنی قبل جوین اجباری و دریافت شماره تلفن از مشتری ، قوانین نمایش داده بشه 
که این قابلیت هم مثل سایر قابلیت ها شخصی سازی بشه و یا دکمه خاموش و روشن داشته باشه که مثل دیوایس ها نشه یک سری ها بخوان و یک سری ها نخوان
**در پایان 3-4 تا پیشنهادی که بالاتر دادم باید بگم واقعا دست مریزاد خیلی برای ما زحمت میکشید و جای تشکر داره ** 
![2](https://github.com/user-attachments/assets/09eda1d7-7d84-4787-93a4-daa6a7169225)

**Comment by Armin02ks** [comment]
سلام اگه امکانش هست کاری کنید روی هر پلنی بخوایم تخفیف اعمال کنیم چون وقتی تخفیف اعمال میکنیم همه پلن های سرور تخفیف شامل میشه

**Comment by mmdkevin** [comment]
لطفا تو پنل وب برای موارد زیر گزینه ادیت هم اضافه کنید تا لینک هارو بتونیم ادیت بزنیم
![image](https://github.com/user-attachments/assets/5b4a7359-0246-477e-bb4f-09cf34cd7c0b)

**Comment by mmdkevin** [comment]
بعضی از یوزر ها ممکنه مثل من لوکیشن هاشون زیاد باشه ، لطفا قابلیتی قرار بدید که بتونیم لوکیشن هارو  از حالت تک خطی در بیاریم یعنی دو تا لوکیشن تو یک خط جا بشه (و البته این مورد هم دکمه تنظیم داشته باشه)
![image](https://github.com/user-attachments/assets/392eab67-af82-4cbc-b620-306cc056c594)

**Comment by mmdkevin** [comment]
> سلام یه مشکلی که وجود داره ایجاد پلن برای سرور هاست اگر هر سرور ۲۰ تا پلن داشته باشه ادم نمیتونه کل سرور هارو اپدیت کنه اگر امکانی باشه که پلن ها مشترک باشه و بشه گروهی توی نسخه وب قیمت هارو ویرایش کرد خیلی خوب میشه

نکته طلایی رو دوست عزیزمون پیشنهاد دادن ، واقعا همچین چیزی امکان پذیر بشه خیلی عالی میشه ، تقاضا داریم که این مورد رو اصلاح کنن و بشه پلن رو به چندین سرور اختصاص داد

**Comment by mmdkevin** [comment]
برای ظرفیت گزینه نامحدود یا بی نهایت هم اضافه بشه
سایر گزینه ها که از پنل وب دسترسی داریم اینجا اضافه بشه 
گزینه تغییر حجم و اینکه مقادیر کمتر از 1 گیگ برای اکانت تست مثلا 0.2 قبول کنه 
![image](https://github.com/user-attachments/assets/f31262f8-8a0e-4cac-b89a-fabb698d54e2)

**Comment by mmdkevin** [comment]
یه موردی هست اینه که ما وقتی کسی رو نماینده میکنیم خرید میکنه وقتی از نمایندگی در میاریمش دیگه کانفیگ هایی که به عنوان نماینده خرید کرده نمایش داده نمیشه براش 
دوباره نماینده میکنیم نمایش میده 

به نظرم یه طوری باشه که در هر 2 حالت هر کانفیگی  که خرید زده نمایش بده منتهی وقتی از نمایندگی در میاد قیمت ها تغییر کنه یعنی وقتی خواست تمدید بزنه قیمت های اصلی رو نشون بده

**Comment by mohsenazade** [comment]
> لطفا تو پنل وب برای موارد زیر گزینه ادیت هم اضافه کنید تا لینک هارو بتونیم ادیت بزنیم ![image](https://private-user-images.githubusercontent.com/133500604/353586598-5b4a7359-0246-477e-bb4f-09cf34cd7c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzYxODksIm5iZiI6MTcyMjM3NTg4OSwicGF0aCI6Ii8xMzM1MDA2MDQvMzUzNTg2NTk4LTViNGE3MzU5LTAyNDYtNDc3ZS1iYjRmLTA5Y2YzNGNkN2MwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQyMTQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzNiNWY5ODJiODZmOTdhZTE0MGZiZmY2ZjBkNmM4ZWMxYzk0YzkzMTU1NWYwYzRiYjViNmZkMTQ1NDU2ZGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lTw1ImHaVlGlZrhx-12uNrGWHYRmOLZUw8Ed2cj2Opk)

اره دقیییقا دکمه ویرایش داشته باشه که هر بار حذف و اضافه نکنیم اخه ترتیب داخل رباتش بهم میریزه از پشت سر هم بودنه

**Comment by mohsenazade** [comment]
لطفا امکان فعال/غیرفعال کردن گزینه کارت به کارت و درگاه پرداخت در بخش های مختلف بزارید
مثلا من میخوام که حالت کارت به کارت فقط در بخش شارژ کیف پول فعال باشه و بقیه بخش ها درگاه پرداخت فعال باشه
و در همون بخش شارژ کیف پول باز گزینه درگاه پرداخت رو بشه خلاصه خاموش کرد

**Comment by MoDorXz** [comment]
یه مورد به نظرم خوبه اضافه بشه برای زمانی ک سرور قطع شده و میخای مثلا لینک موقت فقط به کسایی ک سرویس فعال دارن بدی، با یه گذینه فقط ب اون اشخاص پیام ارسال بشه نه به همه.

**Comment by mmdkevin** [comment]
لطفا قابلیتی قرار بدید که وقتی کسی خرید میکنه یه پروکسی تلگرام هم بهش داخل همون پیام کانفیگ بهش تعلق بگیره که هر وقت پروکسی رو تغییر دادیم یعنی متن رو تغییر دادیم برای مشتری تو قسمت کانفیگ های من هم تغییر کنه 
یا اصلا یه دکمه جداگونه بیاد به نام پروکسی تلگرام (فقط برای کسایی که سرویس فعال دارن)  

که این گزینه پروکسی تلگرام هم مثل سایر ویژگی ها قابلیت تغییرات فعال/غیرفعال کردن داشته باشه

**Comment by mmdkevin** [comment]
یه مورد اصلاحی جزئی هست که بارها برای من اتفاق افتاده :
توی قسمت کانفیگ های من - دکمه **قطع دسترسی و لینک جدید** 
وقتی مشتری این دکمه رو میزنه ربات پاسخ میده لطفا منتظر باشید که همین موضوع باعث میشه مشتری سردرگم بشه و فکر کنه که ربات قرار هست کانفیگ جدید براش بفرسته
اگر این جمله به مثلا "تغییرات اعمال شد" تغییر کنه به نظرم خیلی بهتره 
![Screenshot 2024-08-02 215638 copy](https://github.com/user-attachments/assets/28a2a5b5-d59a-4e9d-b95e-21847949b726)

**Comment by mmdkevin** [comment]
تو قسمت کد تخفیف یه بخشی باشه **کد تخفیف ویژه اولین خرید** رو اعمال کنیم مثل سایت های فروشگاهی دیجی کالا و ...

**Comment by mohsenmalekii** [comment]
> یه مورد اصلاحی جزئی هست که بارها برای من اتفاق افتاده :
> توی قسمت کانفیگ های من - دکمه **قطع دسترسی و لینک جدید** 
> وقتی مشتری این دکمه رو میزنه ربات پاسخ میده لطفا منتظر باشید که همین موضوع باعث میشه مشتری سردرگم بشه و فکر کنه که ربات قرار هست کانفیگ جدید براش بفرسته
> اگر این جمله به مثلا "تغییرات اعمال شد" تغییر کنه به نظرم خیلی بهتره 
> ![Screenshot 2024-08-02 215638 copy](https://github.com/user-attachments/assets/28a2a5b5-d59a-4e9d-b95e-21847949b726)
> 

میتونید از پوشه  values.php تغییرش بدید اگرم روی سرور نصب کردید بگید دستورشو بفرستم

**Comment by iamfarhad** [comment]
توی تنظیمات امکانی باشه که گزینه کارت به کارت برای مشتریان جدید نمایش داده نشه و فقط برای مشتریانب نمایش داده بشه که حداقل یک سفارش موفق پرداخت شده داشته باشند

**Comment by mmdkevin** [comment]
یه مورد اصلاحی هست :
وقتی تیکتی رو پاسخ میدیم اگر **لینک** و یا **کانفیگ** رو ارسال کنیم و یا دریافت کنیم به شکل زیر نمایش داده میشه :
![image](https://github.com/user-attachments/assets/8f777b3a-5faa-437e-9b64-da68c6be24e2)

**Comment by mohsenazade** [comment]
> لطفا قابلیتی قرار بدید که وقتی کسی خرید میکنه یه پروکسی تلگرام هم بهش داخل همون پیام کانفیگ بهش تعلق بگیره که هر وقت پروکسی رو تغییر دادیم یعنی متن رو تغییر دادیم برای مشتری تو قسمت کانفیگ های من هم تغییر کنه یا اصلا یه دکمه جداگونه بیاد به نام پروکسی تلگرام (فقط برای کسایی که سرویس فعال دارن)
> 
> که این گزینه پروکسی تلگرام هم مثل سایر ویژگی ها قابلیت تغییرات فعال/غیرفعال کردن داشته باشه

آخ گفتی کاش بشه این قضیه پروکسی رو حل کرد خیلی وقتا مشتری تمام میشه و به ربات هم سر نزده اختطارشو ببینه بعد تلگرام هم دسترسی نداره تنها راه نجاتش پروکسیه
حالا این پروکسی به چه صورت برسه دست مشتری نمیدونم

**Comment by mohsenazade** [comment]
> توی تنظیمات امکانی باشه که گزینه کارت به کارت برای مشتریان جدید نمایش داده نشه و فقط برای مشتریانب نمایش داده بشه که حداقل یک سفارش موفق پرداخت شده داشته باشند

اره اره لطفا این مورد رو در نظر بگیرید ویز ویز خیلی به کارت میاد
یک جوری گزینه تعداد قرار بدین مثلا بعد 2 خرید موفق با درگاهی چیزی گزینه کارت به کارت رو نشونش بده اینجوری بسیار امنیت میره بالا

**Comment by Sepanta7** [comment]
![Screenshot_۲۰۲۴۰۸۰۴_۱۲۱۸۱۷_Telegram](https://github.com/user-attachments/assets/2b1dcc7e-614a-477c-98e1-16060761062f)
این قسمتی ک دورشو خط کشید تو ولوم وب کاش اون رو حذف کنید

**Comment by Sepanta7** [comment]
کاش ی دکمه هم باشه اکانت های ک کاربران خریدن پلی تو پنل وجود ندارع حذف بشه

**Comment by mmdkevin** [comment]
یک مورد هست که نمیدونم چرا اینطوری میشه !!
من یک بار راس ساعت 12 شب داخل ربات زدم که هر 24 ساعت گزارش درآمد رو به کانال مورد نظر ارسال کنه که هر شب 1 دقیقه اضافه میشه به تایمی که داده بودیم یعنی مثلا شب اول 12:01 میفرسته شب دوم 12:02
کاش این مشکل حل شه و یا بهتر از اون قابلیتی باشه که بشه ساعت تعریف کرد که مثلا بگی راس فلان ساعت ارسال شه

![image](https://github.com/user-attachments/assets/0f77b5e6-843e-4f36-8b61-21298f93254f)
![image](https://github.com/user-attachments/assets/41eb2fda-d9fb-4144-9a0f-80766123cffa)

**Comment by farshadfaza** [comment]
اضافه کردن فعال و غیر فعال کردن کانفیگ برای همه کاربران(بعضیا نمیندن یا فروشندن کانفینگ میدن کاربری پول نداد غیر فعال میکنن که پول بده پول که داد فعال میکنن)



تمدید کانفیگ برای همه کاربران غیراز صاحب کانفیگ(خیلی مهمه الا خودم سر همین نمیتونم به نسخه اخر اپدیت کنم از نسخه قبلی همچنان دارم استفاده میکنم چه اشکالی داره یه کانفیگو همه بتونن تمدید کنن بعضی کاربرا یا فروشنده ها چن نفرن یه اکانت ندارن هربارم نمیتونن کانفیگو انتقال بدن برا اون یکی که تمدید کنن) 

اضافه کردن  اسم به بخش دامنه ها مثلا دو دامنه اضافه کردیم هر دامنه رو یه اسم بزاربم که موقع ارسال لینک اون اسمو بنویس مثلا ایرانسل همراه تامل اینجوری

**Comment by ebisamadi32** [comment]
سلام
اول از همه و مهم تر از همه برگردوندن دامنه ساب به دامنه خود ویز ویز
دوم نام گذاری با سختگیری کمتر.
سوم کلید فعالسازی پنل رو بیارید بیرون تو صفحه ی اول که دیده بشه.
چهارم مساله حذف نکردن کانفیگهای منقضی رو حل کنید لطفا و اینکه گزارش حذف رو هم داشته باشه، که بشه فهمید داره حذف میکنه، البته پیشنهادم برای گزارش حذف اینه که بصورت روزانه باشه، مثلا همه رو آخر شب ارسال کنه که رو مخ نباشه.
پنجم و از همه مهمتر، وقتی چیزی تغییر داده میشه، بجای اینکه به کلی حذفش کنید، اون رو بصورتی تغییر بدید که بشه به حالت قبلی هم استفاده کرد، شاید که نه حتمن بعضیا با اون تغییر موافق نباشن و تو دردسر بیافتن(مثل قضیه ی ساب که برای من مشکل ساز شد واقعا)

**Comment by sarhad-sn** [comment]
سلام 
تایید خودکار کارت به کارت فقط برای نمایندگان بتونیم فعال کنیم

**Comment by mobohes** [comment]
> سلام تایید خودکار کارت به کارت فقط برای نمایندگان بتونیم فعال کنیم

یعنی یه جور شخصی سازی در پرداخت خودکار، خیلی ایده خفنی بود، حتی میتونیم برای یه عده از مشتریان خاص که بهشون اعتماد داریم این قابلیت رو فعال کنیم تا اونا خریداشون شریع تر انجام بشه ( هم برای نماینده ها و هم اشخاص خاص قابل تعریف باشه)

**Comment by sarhad-sn** [comment]
> > سلام تایید خودکار کارت به کارت فقط برای نمایندگان بتونیم فعال کنیم
> 
> یعنی یه جور شخصی سازی در پرداخت خودکار، خیلی ایده خفنی بود، حتی میتونیم برای یه عده از مشتریان خاص که بهشون اعتماد داریم این قابلیت رو فعال کنیم تا اونا خریداشون سریع تر انجام بشه ( هم برای نماینده ها و هم اشخاص خاص قابل تعریف باشه)

بله دقیقا ، خیلی خفن میشه

**Comment by mobohes** [comment]
> توی تنظیمات امکانی باشه که گزینه کارت به کارت برای مشتریان جدید نمایش داده نشه و فقط برای مشتریانب نمایش داده بشه که حداقل یک سفارش موفق پرداخت شده داشته باشند

خیلی موافقم، به نظرم حتی میشه شماره کارت رو به صورت دیفالت برداشت و به جاش یک متن نوشته بشه که چنانچه از مشتریان قدیمی هستید ، شماره کارت رو از ادمین بپرسید و رسید رو داخل ربات ارسال کنید، و چنانچه مشتری جدید هستید از طریق روش های دیگه(رمز ارز) اقدام به خرید سرویس کنید
ساده تر بگم: 
امکان ویرایش متن کارت به کارت به صورت دلخواه (لزومی به نوشتن شماره کارت نیست)

**Comment by Hadihdudj** [comment]
سلام
تخفیف ساعتی روی تمدید هم فعال باشه 
و وقتی کسی از لینک کسی دیگه ربات رو استارت میزنه گزارش رو واسمون بفرسته 
کاربری با یوزرنیم ، آیدی ، با لینک کابر یوزرنیم ، آیدی به ربات پیوست
و وقتی این کاربر خریدی انجام داد پیام بالا + به اندازه ...تومان به حساب فلانی واریز شد

تو کانال گزارش درآمد ،گزارش کامل تری واسمون ارسال کنه
مثلا 
بیاد هر چند پنل داریم 
اسم پنل : .....
خرید های امروز یا هر زمانی که بهش گفتیم: ....
تمدید : ....
اکانت تست : ....
تعداد  کاربر های جدید :  ....
جمع فروش : ....
جمع تمدید: ....
درآمد کل : .....

ارسال کامل گزارش خیلی خوب میشه

**Comment by amirzerok** [comment]
برای پنل مرزبان لینک رو که تحویل میده لینک سابی که کپی لینک رو از تو پنل میزنیم باشه نه لینک خود پنل رو تحویل مشتری بده ممنون

**Comment by milad-ahadpour** [comment]
> پروتکل وایرگارد لطفا اضافه کنید
> 
> برای بخش زبر مجموعه گیری پورسانت به صورت درصد قابل تنظیم باشه
> 
> قابلیت ارسال پیام فقط به مشتریان

لطفا پروتکل وایرگارد رو به نحوی اضافه کنید که بتونه از سرور ایران بخونه و با میکروتیک ست بشه این میشه یه چیز اصولی 
حالا اگه مشکلی با سرور ایران داشته باشه میشه خیلی راحت ترافیک رو اول به سرور خارج فرستاد و بعد از طریق تانل روت کرد به سمت سرور میکروتیک ایران اینجوری کانفینگا هم به مشکل نمیخوره

**Comment by milad-ahadpour** [comment]
زیر مجموعه گیری 

یه موضوعی که خیلی کار امد هست بخش زیر مجموعه گیری هست 
اگه بشه زیر مجموعه گیری به نحوی باشه که درصدی باشه
مثلا مشتری برا خودش زیر مجموعه میگیره و زیر مجموعش هر کانفینگی میگیره همیشه یه مبلغ ثابت به حسابش شارژ میشه و این مورد باعث شده ما کلا زیر مجموعه گیری رو غیرفعال کنیم چون رو پلن های کم حجم صرف نداره . 
ولی اگه درصدی باشه مهم نیست چه پلنی خرید میکنه .

دوستانی که موافقا لایک رو بکوبید 👍🏻

**Comment by mohsenazade** [comment]
لطفا حتما این قابلیت که بعد از تعداد مشخصی خرید مثلا ۲ تا شماره کارت رو نشون بده به کاربران جدید حتما بزارید
در غیر این صورت فقط با درگاه برای دفعات اول

**Comment by mmdkevin** [comment]
فرض کنید ما کلی پلن تعریف کردیم و حالا بعد از مدتی (دقیقا شرح حال همین الان من) میخوایم مثلا داخل دسته دوماهه یه پلن حجم کمتر هم اضافه کنیم 
حالا چه مشکلی پیش میاد؟ ما پلنی که تعریف میکنیم میاد پایینه همه پلن ها
در صورتی که باید به ترتیب قیمت چیده بشه یا به ترتیب گیگ یا هر طوری که ما میخوایم 
پس قابلیتی بزارید بتونیم سطر پلن هارو حداقل جابجا کنیم 
تصویر زیر مثال خوبی هست:
![image](https://github.com/user-attachments/assets/9f42e83e-1a0a-4467-be3f-83f81c0bda2e)

**Comment by mmdkevin** [comment]
وقتی دکمه شارژ کیف پول رو خاموش میکنیم تو قسمت حساب کاربری هم این دکمه از بین میره عملا شارژ کیف پول رو کلا حذف میکنه
ما میخوایم فقط دکمه صفحه اصلی رو برداریم
گزینه ای باشه اینارو مجزا کنه یا کلا این دکمه کاراییش این باشه تو صفحه اصلی نشون نده ولی تو قسمت حساب کاربری باشه
 
![image](https://github.com/user-attachments/assets/8a71f04d-ca67-4a4b-9aa0-acb1752064a6)

**Comment by mmdkevin** [comment]
یه موضوعی هست که دوستان بالاتر اشاره کردن ، اگر پلن هارو بشه یک بار تعریف کرد و به همه سرور ها اختصاص داد خیلی خوب میشه
و اینکه این بخش بصورت سطری باشه اینا خیلی بهتر میشه بنظرم جای کمتری میگیره دسترسی بهتری میده
اصلا یه گزینه باشه بشه تغییر داد بصورت سطری یا این شکلی نمیدونم فکر کنم جعبه ای میشه :D
![image](https://github.com/user-attachments/assets/05287912-f8d0-4c1c-a7b7-9f68e84704d5)

**Comment by mmdkevin** [comment]
یه پیشنهاد جالب!
بعضی مواقع پیش میاد (شرح حال همین الان بنده) مشتری پیام میده :
میخوام کانفیگ رو روی TV - یا یه گوشی ای که دسترسی به هیچ پیام رسانی نداره ، فقط اینترنت داره ، انتقال بدم ، چطوری این کارو کنم ؟!
مسئلةٌ ؟
خب میشه یه لینک خیلی کوتاه مثل کاری که سایت https://ctxt.io (کارش اینه که یه متنی بهش میدی و تایم میدی اونم بهت لینک میده تو این مدت متن داخل این سایت هست و میشه وارد شد کپی کرد) انجام  میده برای مشتری قرار داد که کانفیگ داخل این لینک باشه و به راحتی روی TV یا سایر دیوایس ها با تایپ کردن به URL دسترسی پیدا کنه و کانفیگ رو کپی کنه!
 
پ.ن: منو استخدام کنید روزی 300 تا ایده بدم 😂

![image](https://github.com/user-attachments/assets/928579b0-313a-4c43-87bb-b3bd23792db4)
