### ISSUE TITLE
نماینده

### ISSUE THREAD

**Issue by mahdaviniaali** [wizwizdev/wizwizxui-timebot#1160]
الان نماینده ها رو تمدید ها پورسانت واسشون نمیاد و این خیلی اذیت میکنه ممنون میشم درستشون کنید

و اگه میشه یه کاری کنیم که نماینده ها بتونن به صورت هفتگی یا ماهیانه بدهی رو پرداخت بزنن 
سقف بدهی هم داشته باشه 
و در صورت پرداخت نکردن به ما یگه که پرداخت نشده تو مرحله اول غیر فغال و بعدش پاک بشه

**Comment by wizwizdev** [comment]
رایگان؟

**Comment by Devenat** [comment]
منم رایگانم و این مشکلو دارم
پورسانت واسه تمدید نماینده نمیاد
