### ISSUE TITLE
ناسازگار بودن با نسخه های جدیذ

### ISSUE THREAD

**Issue by Kup1ng** [wizwizdev/wizwizxui-timebot#119]
ریلیتی میخوایم بمولا ولی پنل سنایی یک ماه پیش را داره ربات فقط

**Comment by arian2240** [comment]
> ریلیتی میخوایم بمولا ولی پنل سنایی یک ماه پیش را داره ربات فقط

دوست عزیز باید صبر کنید اپدیت جدید بیاد بعدش بتونید از این پروتکل استفاده کنید

**Comment by wizwizdev** [comment]
اپدیت بعدی میاد
