### ISSUE TITLE
ریمارک

### ISSUE THREAD

**Issue by hamed0mh** [wizwizdev/wizwizxui-timebot#12]
زمانی که یه اکانت میسازی با ربات
 اسم اکانت رو با خیلی اعداد و حروف دیگه قاطی میکنه

.
مثلا ریمارک رو به ربات دادی H-user
زمانی که میسازه اینجوری تحویل میده H-user-135452832- saqwe

**Comment by wizwizdev** [comment]
سلام بله دومی درسته همین مدلیه
