### ISSUE TITLE
درگیر بودن پورت 80

### ISSUE THREAD

**Issue by mohsen3218** [wizwizdev/wizwizxui-timebot#126]
درود این مورد باگ نیست و صرفا یک سوال هست..من میخوام پنل رو نصب کنم ولی بعد از اینکه ایمیل رو وارد میکنم در مرحله بعد میگه پورت 80 درگیر هست و اون برنامه ای ک داره از پورت 80 استفاده میکنه رو متوقف کنید.... این پورت 80 هم پنل سنایی با ssl گرفتنش داره استفاده میکنه خب چاره چیه؟
البته با سروری ک هنوز پنل سنایی ران نشده هم تست کردم و از اول پورت80 ازاد بود ولی وقتی کد نصب پنل شمارو زدم پورت 80رو درگیر کرد و بعدش هم باز این پیام اومد..مشکل چیه؟
میشه ک منظور از پورت 80 دامین باشه و سایتی ک دامین دارم داره پورت80رو استفاده میکنه؟

**Comment by Armingbz** [comment]
ربات رو بايد تو سرور خالى نصب كرد

**Comment by wizwizdev** [comment]
باید پورت 80 روی ربات رو ببندی که مربوط به اپاچی هست به  زودی اموزش میزارم

**Comment by mohsen3218** [comment]
اهاه متوجه شدم..ممنون از پاسختون پس اموزشش رو بزارین من کارم لنگه واس همین مرسی
