### ISSUE TITLE
مشکل در ربات

### ISSUE THREAD

**Issue by karimi-mohammad** [wizwizdev/wizwizxui-timebot#1312]
پنل رو نصب کردم
همه چیز درسته
ولی ربات پیامی رو نمیفرسته 
توی پنل درست تشخیص داده میشه تعداد استارت های ربات
ولی پیامی ارسال نمیکنه
وبهوک هم تنظیم کردم

**Comment by wizwizdev** [comment]
ویدیو توی کانال ببینید یا یوتیویب پره بزنید نصب ویزویز
