### ISSUE TITLE
تمدید با حجم دلخواه 

### ISSUE THREAD

**Issue by Mstrman4** [wizwizdev/wizwizxui-timebot#1313]
سلام وقت بخیر 

میشه کاری کرد وقتی مشتری میخواد تمدید کنه حجم دلخواه تمدید کنه ؟؟ 

مثلا 10  گیگ خریده 30 روزه الان تمدید کنه 40 گیگ 50 روزه

**Comment by alitaka** [comment]
چطوری؟
