### ISSUE TITLE
 مشکل ارسال ناقص کانفیگ در ربات

### ISSUE THREAD

**Issue by amirng** [wizwizdev/wizwizxui-timebot#134]
سلام خسته نباشی واقعا دمت گرم که انقدره پیگیری
یک سوالی الان که ربات در حاله کاره چطوری بیام ادرس سرور رو عوض کنم؟
از طریق دیتابیس یه توضیح میتونی بدی خلاصه خودم پیداش کنم؟

**Comment by arian2240** [comment]
ادرس سرور منظور چیزی که تو قسمت address کلاینت میزنی؟

> سلام خسته نباشی واقعا دمت گرم که انقدره پیگیری یک سوالی الان که ربات در حاله کاره چطوری بیام ادرس سرور رو عوض کنم؟ از طریق دیتابیس یه توضیح میتونی بدی خلاصه خودم پیداش کنم؟

**Comment by amirng** [comment]
اره فکر کنم
من برای پیامی که داخل کانالش گذاشته درخواست گذاشتم

**Comment by amirng** [comment]
سلام 
دمت گرم درست شد به چه سرعتی کار میکنه مثل قبل شد
