### ISSUE TITLE
در حال انتظار ...

### ISSUE THREAD

**Issue by Misakh** [wizwizdev/wizwizxui-timebot#14]
بعد از قرار دادن فایل های bot.php config.php back.php ربات در حالت       ( در حال انتظار ..... ) قرار گرفته
میشه راهنمایی کنید لطفا

**Comment by wizwizdev** [comment]
درود ، این در حال انتظار یعنی هر دکمه ای بزنید مینویسه یا چی؟

**Comment by Misakh** [comment]
هر دکمه ای رو که میزنی هیچ اتفاقی نمی افته 
بات از سمت مشتری مینویسه در حال انتظار ...

**Comment by wizwizdev** [comment]
درست پیش نرفتین یا ی چیزی اشتباهی پاک کردین

**Comment by Misakh** [comment]
دوباره از اول نصب کردم مشکلم حل شد ممنون از زحماتتون و وقتی که میگذارید
