### ISSUE TITLE
token

### ISSUE THREAD

**Issue by sina3600** [wizwizdev/wizwizxui-timebot#15]
سلام موقع نصب

رباتی با این توکن یافت نشد

میده توکن کاملا درسته و از bot father گرفته شده

**Comment by wizwizdev** [comment]
سلام توکن رو اشتباه وارد میکنید برای همین
سعی کنید متن رو کامل کپی کنید و جایگزین کنید همین

**Comment by sina3600** [comment]
ببنید واقعا درست وارد میکنم به این صورت 
0008629297:AAE-RvdIYEQyP9sEn22IXVCZQQRrebAAAA

تغییرات در توکن دادم چون عمومی هست ارسالش در اینجا 
ولی در کادر وارد میکنید به این شکل میشینه 

AAE-RvdIYEQyP9sEn22IXVCZQQRrebAAAA:0008629297



احتمال میدم به خاطر RTL بودن صفحه نصب باشه  ولی توکن به این شکل هست

**Comment by wizwizdev** [comment]
اگ نصب من کار نمیکرد این همه ادم میگفتن کار نمیکنه ، شما به rtl بودن کاری نداشته باشید توکن و بزنید نصب کنید

**Comment by wizwizdev** [comment]
توکن رو هم اینجا نفرستین سواستفاده میکنن ، برید چنج بدید
