### ISSUE TITLE
اضافه کردن برخی قابلیت های کاربردی

### ISSUE THREAD

**Issue by h1rezaei** [wizwizdev/wizwizxui-timebot#17]
سلام بنظرم اینا تو اپدیت های بعدی اضافه شه عالیه

- پشتیبانی از Reality
- پشتیبانی از سایر درگاه پرداخت های ایرانی
- امکان مشاهده و تغییر لینک کاربر بعد از خرید توسط ادمین
- امکان افزودن حجم به کاربر
- امکان تغییر محدودیت کاربر

ارادتمندم

**Comment by h1rezaei** [comment]
و همجنین اینکه بفهمیم کانفیگ برای کیه یا اکانت رو بتونیم غیرفعال کنیم

**Comment by wizwizdev** [comment]
سلام ممنون از شما حتما در نظر گرفته میشه

**Comment by farbodb8368** [comment]
سلام به نظرم تو آپدیت بعدی سیستم دعوت از دوستان هم اضافه بشه برای مثال با دعوت هر کس به ربات و عضو شدن اون شخص در کانال برای فرد دعوت کننده مثلا ۱۰۰۰۰ تومان پاداش بده.

باتشکر از ربات خوبتون
