### ISSUE TITLE
باگ در ایجاد یوزر

### ISSUE THREAD

**Issue by masoud-gb** [wizwizdev/wizwizxui-timebot#18]
سلام خسته نباشی ممنون بابت توسعه این ربات عالی 🙏🌹
ویزویز عزیز ربات یوزرهارو با xtls ایجاد میکنه در حالی که هرگز من ان را انتخاب نکردم.
من از پنل علیرضا استفاده میکنم و ورژن جدید از xtls پشتیبانی نمیکند
با این مشکل امکان ابدیت وجود نخواهد داشت 
پلن جدید در سطر جدید ساختم ربات مجدد xtls را اظافه میکند
با احترام
![Screenshot_20230421_075327_com android chrome_edit_642799768121707](https://user-images.githubusercontent.com/87688187/233577982-a6c9f8ac-fde4-440c-9ee1-99637495d8ba.jpg)

**Comment by wizwizdev** [comment]
سلام عزیز ، پنل علیرضا ورژنی که زده شده فقط کار میکنه و بالاتر کار نمیکنه 
نسخه پنل هم باید 1.7.5 یا 1.6.4 باشه چون نسخه بالاتر مجدد ارور میگیرد
باید از نسخه پاین تر استفاده کنید یا نسخه ای که تو گیت قرار داده شده و گفتم که چه نسخه ای استفاده کنید

**Comment by masoud-gb** [comment]
سپاسگذارم عزیزم 🙏🌹
