### ISSUE TITLE
تحویل ندادن کانفینگ به مشتری

### ISSUE THREAD

**Issue by MrAminiNezhad** [wizwizdev/wizwizxui-timebot#189]
سلام وقت بخیر
من ربات رو ساختم و به پنل متصل کردم و پنل با موفقیت اضافه شده ...
حالا مشکل اینه که کاربر میاد یه سفارش ثبت میکنه و به ادمین برای تایید اطلاع داده میشه ادمین تایید میکنه ولی دکمه تایید سر جاش میمونه ! اما خب بات وارد سرور میشه و کانفینگ رو میسازه البته جای 1 دونه بین 5 تا 12 بار کانفینگ ایجاد میکنه ! و نکته مهم اینه که هیچ کدوم از این کانفینگ هارو تحویل مشتری نمیده ! 
ورژن php 7.4 تنظیم شده ، کرون ها به درستی تنظیم شده ، اکستشن های php به درستی تنظیم شده 
فایل baseinfo.php هم درسته و دامین داخلش وارد شده

**Comment by sinaNJN** [comment]
برو روی سرور ران کن خلاص کن خودتو منم این مشکلات رو داشتم تحویل ندادن - وارد نشدن به سرور و …
 هاست بودم اصلا به دردسرش نمی ارزه روی سرورت بزن همچی خودش اوکی میشه کامل 

رو سرور زدم سرعتش ۱۰۰ برابر هاسته و باگ مرتبط به هاست ها توش نیست فقط یکسری باگ ها مربوط به خود کدنویسی هست ک خودشون باید فیکس کنن تو اپدیت جدید

**Comment by MrAminiNezhad** [comment]
ممکنه مشکل از کرون باشه ؟ 
کرون رو با کامنت زیر تعریف کنم اوکی میشه ؟
php   /home/batwebi7/public_html/wizwizxui-timebot-main/settings/messagewizwiz.php 

سوالات پرتکرار رو خوندم و فایل baseinfo رو درست کردم اما بازم تحویل نمیده

**Comment by MrAminiNezhad** [comment]
> برو روی سرور ران کن خلاص کن خودتو منم این مشکلات رو داشتم تحویل ندادن - وارد نشدن به سرور و … هاست بودم اصلا به دردسرش نمی ارزه روی سرورت بزن همچی خودش اوکی میشه کامل
> 
> رو سرور زدم سرعتش ۱۰۰ برابر هاسته و باگ مرتبط به هاست ها توش نیست فقط یکسری باگ ها مربوط به خود کدنویسی هست ک خودشون باید فیکس کنن تو اپدیت جدید


تست میکنم امید وارم اوکی بشه ...

**Comment by MrAminiNezhad** [comment]
> برو روی سرور ران کن خلاص کن خودتو منم این مشکلات رو داشتم تحویل ندادن - وارد نشدن به سرور و … هاست بودم اصلا به دردسرش نمی ارزه روی سرورت بزن همچی خودش اوکی میشه کامل
> 
> رو سرور زدم سرعتش ۱۰۰ برابر هاسته و باگ مرتبط به هاست ها توش نیست فقط یکسری باگ ها مربوط به خود کدنویسی هست ک خودشون باید فیکس کنن تو اپدیت جدید

نگاه کردم ظاهرا اول باید ویزوویز نصب بشه بعد xui من 100 تا یوزر دارم نمیتونم پنل رو پاک بکنم ! راه کار دیگه نیست ؟

**Comment by wizwizdev** [comment]
لطف از فایل baseinfo خط رو کامل کپی کنید بفرستید اینجا و ب جای دامین خودتون ادرس دیگه ای بزارید

**Comment by MrAminiNezhad** [comment]
> لطف از فایل baseinfo خط رو کامل کپی کنید بفرستید اینجا و ب جای دامین خودتون ادرس دیگه ای بزارید

خدمت شما :

  $botUrl = "https://********.ir/wizwizxui-timebot-main/";

**Comment by behzad666b** [comment]
منم دقیقا همین مشکل دارم

**Comment by wizwizdev** [comment]
از سرور استفاده کنین یا هاست خوب ، چون هر هاستی ی مدله و معلوم نیست مشکل از شماست یا چی به هر حال اگه بدون مشکل میخاین کار کنین فقط سرور بالا بیارین

**Comment by MrAminiNezhad** [comment]
> منم دقیقا همین مشکل دارم

مشکل از هاست بود با تغییر هاست اوکی شد
