### ISSUE TITLE
درخواست اضافه کردن قابلیت کاربردی برای ربات

### ISSUE THREAD

**Issue by farbodb8368** [wizwizdev/wizwizxui-timebot#19]
سلام به نظرم تو آپدیت بعدی سیستم دعوت از دوستان هم اضافه بشه برای مثال با دعوت هر کس به ربات و عضو شدن اون شخص در کانال برای فرد دعوت کننده مثلا ۱۰۰۰۰ تومان پاداش بده.

باتشکر از ربات خوبتون

**Comment by wizwizdev** [comment]
سلام در نظر میگیرم ممنون
