### ISSUE TITLE
پورت اشتراکی vless

### ISSUE THREAD

**Issue by AmoAlireza** [wizwizdev/wizwizxui-timebot#198]
سلام
ربات کانفیگ های که vless هستن و پورت اشتراکی هستن ارسال نمیکنه کلا و qrcode سفید و کانفیگ خالی میفرسته و لینک ساب هم داخلش چیزی نیست احتمال میدم نمیتونه کانفیگ vless رو از json به vless تبدیل کنه.
این مشکل روی پنل سنایی نسخه آخرش و روی سرور اتفاق افتاده و پروتکل همونا وقتی vmess میزارم درست کار میکنه و ارسال میشه همچنین امکانش هست قسمتی که میپرسه id اون کانفیگ چیه بشه چنتا id وارد کرد؟ که روی هر چنتا inbound که وجود داره یدونه یوزر بسازه.

**Comment by AmoAlireza** [comment]
سرور جدا هستش از پنل و کلا یک سرور جدا برای ربات ساختم و داخل ربات قسمت تنظیمات سرور هم تیک reality در هر دو نوع فعال و غیر فعال و همچنین قسمت پلن ها اون قسمتی dest و servernames باید وارد بشه در دو حالتش خالی و پر شده تست شده و بازم نتیجه ای نگرفتم.
داخل ربات هم قسمتی که نوع پروتکل میپرسه vless وارد میکنم و به نظر میرسه این مشکل فقط روی vless http Reality وجود داره مثل نمونه کانفیگ عکس.
![1](https://github.com/wizwizdev/wizwizxui-timebot/assets/79990596/b0601fd9-1480-44b3-8c93-d370ad38f9b2)

![2](https://github.com/wizwizdev/wizwizxui-timebot/assets/79990596/01bc2e4c-215a-4007-aae9-71708aa43dc3)

**Comment by AmoAlireza** [comment]
پنل سنایی.
![Capture](https://github.com/wizwizdev/wizwizxui-timebot/assets/79990596/de49f392-c3f9-4854-a3e0-d33ecf79c876)

**Comment by AmoAlireza** [comment]
همیشه اینطوره حتی چند بار سرور کلا پاک کردم و از اول ساختم ولی باز همینطور میشد سرورم هم خارجه.

**Comment by wizwizdev** [comment]
منظورم اینه  پنل x-ui شما روی سرور ایران نصب شده یا خارج؟

**Comment by AmoAlireza** [comment]
یه نکته ای یادم رفت بگم اینه که وقتی تو هتزنر سرور خاموش میکنم و IP عوض میکنم و یه جدید جایگزین قبلی میکنم با اینکه پشت دامین هم میزارم و دامین عوض نمیشه ربات تلگرام از کار میفته و فقط پنل کار میکنه اینو باید چطور حلش کرد؟

**Comment by wizwizdev** [comment]
روی پنل سنایی چیزی که گفتین ناقص میفرسته کانفیگ ایجاد میشه یا اونجا هم ایجاد نمیشه؟

**Comment by AmoAlireza** [comment]
نه کانفیگ درست میسازه و کامل بدون مشکل داخل خود پنل سنایی ولی ربات موقع ارسال کانفیگ خالی میفرسته.

**Comment by wizwizdev** [comment]
تازه دقت کردم فهمیدم شما نوع شبکه تون h2 که کلا تو بات نداریم همچین چیزی از اونه احتمالا

**Comment by AmoAlireza** [comment]
بله تازه دیدم داخل کد ها کلا شما transmission http اضافه نکردین.

**Comment by wizwizdev** [comment]
ریلیتی tcp بزنید مثل بقیه بچه ها

**Comment by AmoAlireza** [comment]
بله تشکر در اینده روی سورس اصلی بیزحمت اضافه کنید.
