### ISSUE TITLE
مشکل در ثبت سرور جدید

### ISSUE THREAD

**Issue by irpicsi** [wizwizdev/wizwizxui-timebot#202]
سلام
وقت بخیر من ربات ویزویز رو روی هاست سی‌پنل نصب کردم
همه چیز درست کار میکنه جز ثبت سرور، مشکل هم اینجاست که وقتی تا مرحله ۷ که ثبت سرور هست میرم بعدش میزنه با خطا مواجه شدی....
همه اطلاعات وارد شده هم درسته...
آیا کسی سرور تونسته روی ربات که روی هاست نصب شده وصل کنه؟
میگن باید پورت پنل باز باشه روی سرور (خب اینکه هیچ هاستی زیر بارش نمیره!)
اصلا شدنیه؟

**Comment by Mmd20193** [comment]
سلام 
بنده با پورت 8443 انجام دادم مشکلی نداشته

**Comment by Real-kia** [comment]
روی 8080 تست کن
دقت کن که ادرس پنل درست وارد کنی
حتی یه / زیادی نزاری
به http و https هم دقت کن

**Comment by mailsupnt** [comment]
سلام
آدرس پنل رو به اینصورت وارد کن
اگه https هست 
https://yourdomain.com:54321
اگه با ip هست
http://125.12.12.36:54321 
و یک مورد دیگه اگه توی پنل x-ui قسمت path رو فعال کردی به این صورت وارد کن 
https://yourdomain.com:54321/path

http://125.12.12.36:54321/path
