### ISSUE TITLE
راه اندازی یک ربات مشابه با این برای فروش فایل در تلگرام

### ISSUE THREAD

**Issue by ccirco** [wizwizdev/wizwizxui-timebot#209]
من نیاز دارم برای یک ربات فروش فایل با رمز ارزها در تلگرام با شما ارتباط بر قرار کنم ربات به زیان انگلیسی کامل باشد
مشابه همین پروژه فروش اکانت است به جای اکانت فایل بفروشه ربات
لطفا به من در تلگرام پیام دهید
@expimp

**Comment by wizwizdev** [comment]
متاسفانه پروژه قبول نمیکنم
