### ISSUE TITLE
ورود به پنل نا موفق

### ISSUE THREAD

**Issue by hayatisaeed** [wizwizdev/wizwizxui-timebot#21]
من از xui ورژن 1.6.4 دارم استفاده میکنم، حین اضافه کردن سرور، با وجود درست بودن پسورد و یوزرنیم، این پیام رو نشون میده:
اطلاعاتی که وارد کردی اشتباهه، مجدد پسوردت رو وارد کن.

**Comment by wizwizdev** [comment]
گیت و نصفه نمیه نخونین ، این قسمت و با دقت بخونید
https://github.com/wizwizdev/wizwizxui-timebot/blob/main/education/host-persian.md#تنظیمات-ربات

**Comment by hayatisaeed** [comment]
مراحل رو طبق اسکرین شات ها طی کردم. همچنان همونی هست که بود.
![2023-04-26 08 35 34](https://user-images.githubusercontent.com/79208412/234474999-e50dd2a1-aa5d-4fe5-b884-76e4264a9a14.jpg)

**Comment by Maxbow2023** [comment]
سلام من تازگی ها دیگه نمی‌تونم پنلم به ربات وصل کنم یعنی وصل نمیشه میشه هم کانفیگ نمیسازع میگه مشکلی پیش اومد سریع به مدیر بگو ‼️
و پنلم سناعی
لطفاً کمک کنید مشکل از پورت هم نیست تیکت دادم هاست پورت 8443 باز و اونو گذاشتم
باز هم درست نشد

**Comment by Misakh** [comment]
> [Maxbow2023](/Maxbow2023)

منم همین مشکل رو دارم

**Comment by wizwizdev** [comment]
> مراحل رو طبق اسکرین شات ها طی کردم. همچنان همونی هست که بود. ![2023-04-26 08 35 34](https://user-images.githubusercontent.com/79208412/234474999-e50dd2a1-aa5d-4fe5-b884-76e4264a9a14.jpg)

 برید گیت و بخونید چیزی که تو گیت نوشتم و رعایت نکردین
