### ISSUE TITLE
باگ تمدید

### ISSUE THREAD

**Issue by iman5750** [wizwizdev/wizwizxui-timebot#23]
اگر کاربر درخواست تمدید را با اسکرین شات واریز، ارسال کند ، مدیر با مشکل تایید روبرو میشود . ادمین با کلیک روی گزینه تایید هیچ پیغامی دریافت نمیکند ولی سرویس تمدید میشود . اما اگر کاربر درخواست تمدید را با متن( کد پیگیری واریز ) ارسال کند این مشکل وجود ندارد

**Comment by arian2240** [comment]
همچنین هنگامی که حتی با دسترسی مدیر تمدید سرویس را میزنیم چه به صورت کارت به کارت و چه به صورت کیف پول پیام سرویس تمدید شد دریافت میشود ولی در عمل تمدید نمیشود

**Comment by wizwizdev** [comment]
> اگر کاربر درخواست تمدید را با اسکرین شات واریز، ارسال کند ، مدیر با مشکل تایید روبرو میشود . ادمین با کلیک روی گزینه تایید هیچ پیغامی دریافت نمیکند ولی سرویس تمدید میشود . اما اگر کاربر درخواست تمدید را با متن( کد پیگیری واریز ) ارسال کند این مشکل وجود ندارد

رفع میشه اپدیت بعد

**Comment by wizwizdev** [comment]
> همچنین هنگامی که حتی با دسترسی مدیر تمدید سرویس را میزنیم چه به صورت کارت به کارت و چه به صورت کیف پول پیام سرویس تمدید شد دریافت میشود ولی در عمل تمدید نمیشود

نسخه های که گفته شده استفاده کنید تمدید میشه

**Comment by 66Hamidreza** [comment]
من هم این مشکل رو دارم !
 روی 3 پنل این مشکل وجود داره نوع پنل هم نیدوکا هست

**Comment by wizwizdev** [comment]
> من هم این مشکل رو دارم ! روی 3 پنل این مشکل وجود داره نوع پنل هم نیدوکا هست

اپدیت بیاد رفع میشه
