### ISSUE TITLE
بخش تیکت باگ داره

### ISSUE THREAD

**Issue by Amirmcir** [wizwizdev/wizwizxui-timebot#243]
سلام مهندس عزیز مون خداقوت
داخل بخش تیکت یه باگی که وجود داره
کاربر میاد مخاطب موردنظرش رو انتخاب میکنه
مثلا واحد فنی 
بعد ربات میگه تایتل گفتگوت چیه
کاربرم میگه مثلا ایکس
بعد اون ربات باید بگه خب مشکلتو بگو تا بفرستم
اما بعد از ارسال پیام تایتلت رو مشخص کن ربات قفل میکنه و هیچ پاسخی رو دریافت نمیکنه و عملا باگ داره
توی نسخه جدید اینطوری شده
سورسم نگا کردم دقیقا عین قبله نمیدونم مشکل از کدوم قسمته
وقت کردی حلش کن

و اینکه یه دکمه بزار بخش
 پشتیبانی رو بشه روشن یا خاموش کرد

**Comment by wizwizdev** [comment]
سلام
احتمالا مشکل از هاست باشه چون همین الان تست کردم مشکلی نداشت

**Comment by Amirmcir** [comment]
> سلام احتمالا مشکل از هاست باشه چون همین الان تست کردم مشکلی نداشت

روی سرور نصبه و اپدیت هم انجام شده همچنان همین طوریه

**Comment by Amirmcir** [comment]
> ندارم همچین مشکلی متاسفانه وقتی خودم ندارم نمیتونم بفهمم باگه یا چی ، شاید ی تنظیمی چیزی دست زدین اینطوری شده

اتفاقا خودمم به همین فکر بودم شاید خودم دستکاری کردم و مجدد ربات و پنل رو اپدیت کردم حل نشد
اطلاعات بدم چک کنید؟

**Comment by wizwizdev** [comment]
ربات رو بفرستید به بچه ها میگم تست کنن

**Comment by Amirmcir** [comment]
> ربات رو بفرستید به بچه ها میگم تست کنن
@AmirVPNProBot

**Comment by Amirmcir** [comment]
> شماره رو غیرفعال کنید از توش

غیرفعال شد

**Comment by wizwizdev** [comment]
لطف کنین دسته بندی که ایجاد کردین رو بدون ایموجی بزارین ، احتمالا به خاطر ایموجی هست

**Comment by Amirmcir** [comment]
> لطف کنین دسته بندی که ایجاد کردین رو بدون ایموجی بزارین ، احتمالا به خاطر ایموجی هست

بعله مشکل به همین خاطر بود حل شد
یه دنیا تشکر ♥️♥️

**Comment by Amirmcir** [comment]
دوستان تمام گفتگو رو بخونید این مشکلم حل شد
