### ISSUE TITLE
 بک آپ گرفتن از دیتابیس ربات اتوماتیک

### ISSUE THREAD

**Issue by Real-kia** [wizwizdev/wizwizxui-timebot#251]
سلام
یه مشکلی که خودم داشتم دوست داشتم از دیتابیس خود ربات بتونم به صورت اتوماتیک (توی سرور ) بک آپ بگیرم 
https://github.com/Real-kia/wizwiztools
با این اسکریپت میشه
گفتم شاید دوستان هم این مشکل داشته باشن
اگه سوالی یا مشکلی بود issue باز کنین بهم بگین

**Comment by wizwizdev** [comment]
دستور اپدیت رو بزنید نوشته بک اپ فک کنم شماره 3 باشه

**Comment by Real-kia** [comment]
خب اره درست میگین
ولی باید هر وقت میخوام بک اپ بگیرم
به صورت دستی بگیرم
این اسکریپت برا اینه که مثلا هر روز خودش بگیره
اینجوری
