### ISSUE TITLE
مجموعه ای از باگ ها و پیشنهاد های قابل تأمل

### ISSUE THREAD

**Issue by SeniorAminam** [wizwizdev/wizwizxui-timebot#259]
با عرض سلام و خسته‌ نباشید 

اول از همه جا داره به خاطر این امکانات فرا خوبی که در اختیار ما قرار دادید از طرف همه ازتون تشکر کنم 

من یه چند روزیه که دارم روی سورس شما وقت میزارم

و به چند تا باگ برخوردم که گفتم بهتون اطلاع بدم تا توی تایم ازادتون و اپدیت های بعدی اگر صلاح دونستید این باگ ها را رفع کنید 

در ادامه چند تا پیشنهاد برای ارتقا دادن ربات هم بهتون میدم که امیدوارم مورد تایید شما قرار بگیره

باگ ها 

۱. روی سروری که از قبل روش پنل ران شده نمیشه این ربات رو ران کرد

( حتی با وجود اینکه با استفاده از دستور

nano /etc/apache2/ports.conf 

دستور Listen To Port 80 رو کامنت کردم )

۲. به رباتی که روی هاست ران شده تحت هیچ شرایطی نمیشه سرور اضافه کرد 

۳. از طریق پنل ربات شما که روی دامین ران میشه نمیشه سرور اضافه کرد یا تغییراتی رو ایجاد کرد 

۴. تشخیص ندادن اینکه از قبل برای دامین یا ساب دامین Ssl فعال شده و دیگه پیشنهاد ندادنش

پیشنهاد ها 

۱. تشخيص دادن از قبل نصب بودن پنل و پیشنهاد دادن اتصال به پنل تشخیص داده شده در سرور

۲. اضافه شدن یک دکمه اختصاصی که بعد از اضافه شدن سرور به ربات یا ست شدنش با پنل از قبل نصب شده اینباندز ها رو نشون بده و بشه اونا را مدیریت کرد

اینطوری اگه از طریق ربات هم نشه پلن ساخت میشه از طریق خودِ پنل چند تا پلن ساخت و با استفاده از همون پلن ها با کمک ربات کلاینت به اینباندز ها اضافه کرد 

۳. پیشنهاد دادن برای نصب کردن پنل های مورد تایید خودتون با استفاده از وارد کردن شماره ( یعنی به طور مثال از ۱ تا ۶ پنل های مورد تایید خودتون رو پیشنهاد بده ) بعد از نصب شدن خودِ ربات در سرور

و در اخر امیدوارم که در تمام مراحل زندگی اول سلامت و بعد موفق باشید

**Comment by wizwizdev** [comment]
سلام ممنونم

مورد 1 دیگ مربوط به سرور شماست از هرجا گرفتین به خودش بگید 
مورد 2 و3 و4 تو کانال گفتم هاست کلا مشکل داره وبرای راحتی باید روی سرور نصب کنین

در مورد پیشنهاد هم ببینیم چی میشه
