### ISSUE TITLE
افزودن پنل جدید

### ISSUE THREAD

**Issue by hadi7000** [wizwizdev/wizwizxui-timebot#267]
سلام. 
میخاستم ببینم میشه پنل مرزبان اضافه بشه به ویز ویز؟ 
ربات شما عملن برای فروش طراحی شده ولی از بهترین پنل برای فروش پشتیبانی نمیکنه!
ادمین های مرزبان خیلی آدمای درست و باحالین زیادم آپدیت بیخود و بی جهت هم نمیدن که کار شما برای ربات سخت بشه، اگه امکانش هست این پنل رو اضافه کنید، تنها پنل ایرانیه که از قابلیت پنل مرکزی (نود) پشتیبانی میکنه، خیلی از بچه های ایرانی از این پنل استفاده میکنن و اینکه ربات شما این پنل رو پشتیبانی نمیکنه خیلی بده. 
بازم ممنون بخاطر زحماتت.

**Comment by wizwizdev** [comment]
سلام متاسفانه خیر اضافه نمیشه
