### ISSUE TITLE
پیشنهاد برایجلوگیری از لاگین متعدد

### ISSUE THREAD

**Issue by MrAminiNezhad** [wizwizdev/wizwizxui-timebot#282]
سلام خدمت شما ، یه پیشنهادی برای جلوگیری از لاگین های زیاد به سرور داشتم... جای اینکه ربات بیاد هر بار اقدام به لاگین بکنه توسط فایل مثلا login.php لاگین بکنه و یک فایل کوکی ایجاد کنه مثلا به صورت فایل txt سپس برای هر بار لاگین اول بیاد چک بکنه ببینه اون کوکی هنوز معتبر هست یا نه اگه معتبر بود که وارد پنل بشه کاری که میخواد رو انجام بده ... اما اگه معتبر نبود بیاد مجدد با کمک فایل login.php لاگین بکنه و کوکی جدید رو ذخیره بکنه...

**Comment by wizwizdev** [comment]
سلام قبلا همین مدلی بود و مشکلات دیگه ای داشت که تغییر کرد

**Comment by wizwizdev** [comment]
و این لاگین کردن فقط مربوط به کرون جاب هست و کاریش نمیشه کرد

**Comment by MrAminiNezhad** [comment]
درست ، موارد مروبط به اون 3 فایل کرون چقدر مهمه ؟ من نگاه کردم موارد خاصی توش نیست بجز ارسال همگانی ... فک کنم باقی رو بشه روی 12 ساعت گذاشت درسته ؟

**Comment by wizwizdev** [comment]
هرچقدر مقدار بالا باشه دیر تر به کاربر ارسال میشه فرض کنین 100 تا کاربر دارین و این مقدار تقسیم میشه بین همه ، کسی که الان موجودیش یک گیگ شاید تا ی ساعت دیگ تموم کنه و اعلان براش نمیره

**Comment by wizwizdev** [comment]
شما چرا مشکل دارین با لاگین ، چیز خاصی پیش نمیاد خب

**Comment by MrAminiNezhad** [comment]
> هرچقدر مقدار بالا باشه دیر تر به کاربر ارسال میشه فرض کنین 100 تا کاربر دارین و این مقدار تقسیم میشه بین همه ، کسی که الان موجودیش یک گیگ شاید تا ی ساعت دیگ تموم کنه و اعلان براش نمیره

درست پس نیازه بین 1 تا 5 دقیقه تنظیم بشه

**Comment by MrAminiNezhad** [comment]
> شما چرا مشکل دارین با لاگین ، چیز خاصی پیش نمیاد خب

اخه حقیقت مشکلاتی رو دارم توی گروه میبینم که البته مربوط به ویز ویز نیست اونم لو رفتن پورت هست ( طرف میاد اسکن میکنه و پورت رو پیدا میکنه ) و تلاش یک عده برای لاگین به پنل سرور x-ui از اونجایی که ویزویز نمیتونه ورود ناموفق رو نشون بده ممکنه اطلاعات پنل لو بره و دردسر بشه ... چون ادمین متوجه نمیشه که یکی داره سعی میکنه وارد پنل بشه و بیاد سریع پورت رو عوض بکنه ....

**Comment by irpicsi** [comment]
شما پورت رو تغییر بده و نام کاربری و پسورد و path پیچیده تعریف کن/ تامام
