### ISSUE TITLE
باگ گیر کردن بات

### ISSUE THREAD

**Issue by AmoAlireza** [wizwizdev/wizwizxui-timebot#290]
سلام
یه باگ جدیدی افتاده تو ربات همه چیزش اوکیه و ربات خیلی سریع و درست کار میکنه ولی تا میری قسمت افزودن پلن اختصاصی و اشتراکی و روش میزنی بات هنگ میکنه و دیگه هیچیش کار نمیکنه سرور هم از اول پاک کردم وساختم ولی مشکل حل نشد.

**Comment by wizwizdev** [comment]
سلام بررسی میکنم
