### ISSUE TITLE
باگ تکرار ارسال پیام

### ISSUE THREAD

**Issue by AmoAlireza** [wizwizdev/wizwizxui-timebot#299]
سلام
باگ تکرار پیام ربات وقتی مثلا start میزنی 2 بار پشت هم جواب میده و وقتی اتفاق میفته که ربات ازت یه چیزی میخواد مثلا اسم دستبه بندی گزاشتن که 2 بار ازت میپرسه یه اسم برای دسته بندی انتخاب کن.

اینم یه نمونه
![Capture](https://github.com/wizwizdev/wizwizxui-timebot/assets/79990596/aa88aeb0-4d19-4e11-a5bc-292c5c54adda)

**Comment by wizwizdev** [comment]
هاست یا سرور؟

**Comment by AmoAlireza** [comment]
سرور ubuntu نصبشم تاره انجام دادم بعد  دیدن پیامتون تو تلگرام.

**Comment by AmoAlireza** [comment]
سرور از توی هتزنر کلا من وقتی کارم تموم میشه پاک میکنم که مشکلی پیش نیاد.

**Comment by AmoAlireza** [comment]
الان یه بار دیگه کلا سرور پاک میکنم و نصب میکنم اطلاع میدم.

**Comment by AmoAlireza** [comment]
مشکل حل شد.

راه حل:
اگر از قبل توی ربات چت بفرستید منظورم قبل از راه اندازی wizwiz مثلا پیام (😪 منصرف شدم بیخیال) من چندین بار فرستاده بودم و start فرستاده بودم اینطور باگ شده بود و باید سرور از rebuild کنید.
