### ISSUE TITLE
ربات راه اندازی نمیشه

### ISSUE THREAD

**Issue by aliamg1356** [wizwizdev/wizwizxui-timebot#3]
با درود و خسته نباشید.ربات رو هاست نصب میشه و همه چی ظاهرا درسته ولی ربات در تلگرام هیچ عملی انجام نمیده

**Comment by wizwizdev** [comment]
سلام عزیز ، لوکیشن هاست کجاست؟

**Comment by aliamg1356** [comment]
> سلام عزیز ، لوکیشن هاست کجاست؟
ربات نصب میشه ولی قط یک پیام میفرسته با مضمون ارسال پیام همگانی و تمام .بعد اون هیچ کاری انجام نمیده دیگه و هیچ گزینه ای نمیاد
