### ISSUE TITLE
باگ تو ریلیتی

### ISSUE THREAD

**Issue by HellthonAriya** [wizwizdev/wizwizxui-timebot#303]
داداش تروخدا این چی بود مارو باز خمار گذاشتی:((((((
ریلیتی گفته بودم flow=none بذار ببین چجور گذاشتی
flow=' .  .'&
تو پنل هم همینو وارد میکنه

**Comment by HellthonAriya** [comment]
تروخدا قبل اینکه بزنی آپدیت بدی بگو کجاش باید ادیت شه دستی ادیت کنم چون من برا چنجای ربات مجبور شدم یه فورک بزنم اینطوری باید کلهم دوباره از اول ادیتامو انجام بدم.بگو تروخدا زود کجارو باید ادیت کنم

**Comment by HellthonAriya** [comment]
همچنین وقتی اسپایدرایکس خالیه اصن نباید بنویسه spx= همینطوری الکی

**Comment by wizwizdev** [comment]
سوالات پرتکرار نوشته شده

**Comment by HellthonAriya** [comment]
> سوالات پرتکرار نوشته شده

اقا بخدا رعایت کردم هنوز همین وضعیته
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/33875622/f7a78181-d810-44ea-be70-17ccd37f086f)
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/33875622/d50c3e35-47f5-4d6b-90e4-f125896acd91)
دیگه چی باید وارد کنم همش کامله دیگه
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/33875622/8d418171-813b-420c-98b6-96be3a7e309c)

**Comment by HellthonAriya** [comment]
من پنلم سناییه بذارین رو علیرضا هم تست کنم ببینم

**Comment by wizwizdev** [comment]
من تو سنایی درست کردم به خاطر حرف شما تازه رفتم علیرضا فرستادم دوتاشم یکیه

**Comment by HellthonAriya** [comment]
اقا الان دوباره رو هر دوتاش تست کردم بخدا همینه از اول هم دوباره سرور رو اد کردم
هم اولش با sni هم بی sni
کامل طبق توضیحات بعد میرم اون چارتا کادرم پر میکنم همه چیش اکی ولی اونطوری پر میکنه کادرو
