### ISSUE TITLE
باگ vless http reality

### ISSUE THREAD

**Issue by AmoAlireza** [wizwizdev/wizwizxui-timebot#307]
هنوز باگ که توی این #198  گفتم حل نشده.

![Capture](https://github.com/wizwizdev/wizwizxui-timebot/assets/79990596/0cf2d0ae-f8fe-4fc7-9278-3f8f390bd4e5)

**Comment by wizwizdev** [comment]
لطف کنین سولاات پرتکرار رو بخونید دیشب گفتم چیکار کنین

**Comment by AmoAlireza** [comment]
تست کردم فرقی نکرد و فایروال خاموش با allow کردن یه port خاص فرقی نمیکنه ها.

**Comment by wizwizdev** [comment]
شما صددرصد پنل XUI تون روی ایرانه برای همین مشکل رو دارید و مشکلش هم بالا گفتم با اون رفع میشه البته فقط روی سرور با این روش حل میشه و اگه درست انجام داده باشین و بلد باشین چجوری فعال میکنن

**Comment by AmoAlireza** [comment]
اگر به این باور دارین که هتزنر داره سرور ایران میفروشه و من اشتباهی سرور ایران خریدم که خب هیچی و نگران نباشید به اندازه کافی بلدم :)
در هر صورت دمت گرم بابت این سورس رایگان اگر وقت کردم خودم مشکلشو پیدا میکنم و pull request میدم شما هم اضافه کنید.

**Comment by wizwizdev** [comment]
> اگر به این باور دارین که هتزنر داره سرور ایران میفروشه و من اشتباهی سرور ایران خریدم که خب هیچی و نگران نباشید به اندازه کافی بلدم :) در هر صورت دمت گرم بابت این سورس رایگان اگر وقت کردم خودم مشکلشو پیدا میکنم و pull request میدم شما هم اضافه کنید.

گفتم که مشکل چی هست و دیروز برای 3 نفر فرستادم حل شد و مشکل از اپدیت سنایی هست
