### ISSUE TITLE
ارور در هنگام نصب بر روی سرور

### ISSUE THREAD

**Issue by Mhmansouri** [wizwizdev/wizwizxui-timebot#318]
ubuntu: 20.4
datacenter: DigitalOcean

در هنگام نصب به این ارور برخورد کردم؟! میشه اگر کسی این مشکل رو داشته راهنمایی کنه؟

Error:
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> Error installing lamp-server^

**Comment by wizwizdev** [comment]
این و بخونید

**Comment by wizwizdev** [comment]
https://github.com/wizwizdev/wizwizxui-timebot/issues/265#issuecomment-1581139526

**Comment by Mhmansouri** [comment]
> [#265 (comment)](https://github.com/wizwizdev/wizwizxui-timebot/issues/265#issuecomment-1581139526)

خیلی متشکرم از پاسخگوییت...
