### ISSUE TITLE
نصب موفق روی سرور ولی عدم کارکردن ربات

### ISSUE THREAD

**Issue by alamdari86** [wizwizdev/wizwizxui-timebot#329]
سلام و خسته نباشید
من دامنه رو با هاست از طربق کلا فلر ست میکنم و نصب ربات رو انجام میدم 
پیغام نصب موفق نیز از طریق ربات برام ارسال میشه ولی وقتی استارت میزنم پاسخی دریافت نمی کنم

**Comment by Morghak963** [comment]
من دقیقا همین مشکل رو با سرور دارم 
روی سرور نصب میشه، پیام هم میاد ولی کار نمیکنه
حتی دادم سرور رو یکی از دوستان که انجام داده بود تست کرد اونم نتونست

**Comment by 20elias01** [comment]
منم همین مشکل رو دارم کسی راه حل نداده ؟
