### ISSUE TITLE
باگ تمدید و خرید

### ISSUE THREAD

**Issue by saeedhp32** [wizwizdev/wizwizxui-timebot#33]
سلام کاربر وقتی میخواد اشتراکشو تمدید کنه بعد از پرداخت داخل صفحه ی پرداخت میگه اشتراکتون تمدید شد ولی داخل ربات پیامی ارسال نمیشه واسش و همچنین برای مدیر ربات چیزی نمیگه که این خرید انجام شده بابت تمدید بوده. و این مورد بعضی موقع ها واسه خرید کانفیگ جدید هم صدق میکنه

**Comment by wizwizdev** [comment]
مورد بررسی قرار میگیره حتما
