### ISSUE TITLE
weswap

### ISSUE THREAD

**Issue by darhelm** [wizwizdev/wizwizxui-timebot#357]
لینکی که ربات جنریت میکنه با api اصلا با والت مقصد من همخونی نداره
weswap در اخر لینک میاد ولت مقصد رو هرچی میخواد میزنه 
صرفا برای تست اومدم ببینم خرید هام قبول میشن یا نه والت فقط weswap زده که بعد خودش بریزه به حساب دیدم نه با اینکه payment accept میشه از طرف ربات پولی به والت من نرفت
از trust wallet استفاده میکنم
والت رو دادم به nowpayments و api key رو از payment settings برای trx گرفتم ولی باز هم حتی وقتی چندبار api key رو عوض میکنم یا والت رو دوباره میزنم درست نمیشه با والت wallex هم امتحان کردم دیدم ربطی به والت نداره یا مشکل از ربات هست که والت رو اشتباه میزنه یا api تو ریسپانس داره والت اشتباه میفرسته

**Comment by wizwizdev** [comment]
نمیدونم چون همجین مشکلی ندیدم و باید مستقیم بره تو ولت
من از تراست ولت استفاده کردم البته فکر نمیکنم به این ربط داشته باشه شمام تست کنین

**Comment by darhelm** [comment]
> نمیدونم چون همجین مشکلی ندیدم و باید مستقیم بره تو ولت من از تراست ولت استفاده کردم البته فکر نمیکنم به این ربط داشته باشه شمام تست کنین

من هم با تراست ولت زدم ولی حتی بعد تکمیل تراکنش حسابم خالیه ادرس ولت و اینا همچی درست بود
برای شما ربات لینک  weswap جنریت میکنه ادرس والت خودتون رو میزنه؟ممنون میشم چک کنید 
مثال من لینک https://weswap.digital/quick?amount=9.7&currency=TRX&address=TNvTFNu5d4jbSUq5q5Gqk7L8TWHt6VZQ7w
رو میگیرم ولی آدرس ولتم داخل nowpayments 
TFtaRFKJJrhtE85*********wuUmjwT1
هست
البته این الان دیگه trust wallet نیستش

**Comment by wizwizdev** [comment]
این درسته نمیفرسته برای کیف پول شما من نمیدونم از چی میتونه باشه شما تراس ولت ندارین ی تست کنین؟ البته نمیدونم دلیلش چیه حالا تست ضرر نداره

**Comment by darhelm** [comment]
> این درسته نمیفرسته برای کیف پول شما من نمیدونم از چی میتونه باشه شما تراس ولت ندارین ی تست کنین؟ البته نمیدونم دلیلش چیه حالا تست ضرر نداره

دارم خب با اون زده بودم اول حتی پرداختم کردم و قبول هم شد نمیدونم چطور وریفای شد دقیقا احتمالا به نوبه ای api ولت مقصدو بررسی کرده دیده ۴ بار وریفای شده زده ولی پولی به ولت من ننشست
حالا پول تو nowpayments والتی که برگردونده رفته باید یطوری بگیرم پول رو یا فقط api داره ولت اشتباهو بر میگردونه

**Comment by wizwizdev** [comment]
نه  اون خودش اینطوری نشون میده این که به حساب شما نمیشینه عجیبه شما ی لطفی کن تراس ولت هم تست کن البته فک نمیکنم ربطی داشته باشه

**Comment by darhelm** [comment]
> نه اون خودش اینطوری نشون میده این که به حساب شما نمیشینه عجیبه

دم شما گرم نشست ولی ۱ روز حدودا طول کشید فکر نمیکردم انقدر طول بکشه دفعه اول بود
ممنون بابت ربات و روش
<3

**Comment by wizwizdev** [comment]
شاید از شانس شما بوده چون نهایتش 10 دقیقه میشینه
