### ISSUE TITLE
آپدبت به ورژن جدید در هاست 

### ISSUE THREAD

**Issue by mostafacpr** [wizwizdev/wizwizxui-timebot#37]
ضمن عرض سلام و خسته نباشید
۱.لطفا بفرمایید درصورت نیاز به نصب مجدد پروژه کدوم فایلهارو از هاست بکاپ بگیریم که دیتا پاک نشه 
۲. برای آپدیت مجدد دانلود کنیم کپی کنبم داخل هاست یا از طریق لینک راه اندازی دکمه آپدیت ربات رو بزنیم؟
باتشکر از زحمات شما

**Comment by wizwizdev** [comment]
سلام
اگه میخاید مجدد نصب کنید باید دیتابیس رو بک اپ بگیرید که از طریق phpmyadmin اینکار انجام میشه و بعد از نصب مجدد فایل دیتابیس رو ایمپورت کنید همین
برای اپدیت داخل هاست حتما باید تو کانال عضو باشید که توضیح بدم چیکار بکنید شرایط یکم فرق داره
ولی سرور با ی دستور اپدیت میشه
برای بک اپ هم تو گوگل میتونید جست و جو کنید ، ی اموزش برای این بک اپ دیتابیس هم به زودی اماده میشه

**Comment by mostafacpr** [comment]
تشکر از زحمات شما
