### ISSUE TITLE
پلن رهگذر برای تست در ریلیتی

### ISSUE THREAD

**Issue by yazdaniyan73** [wizwizdev/wizwizxui-timebot#388]
درود و خدا قوت خدمتتون
ویز ویز نصب شده در سرور
من ریلیتی کار مکنم اکانت تست در رهگذر فعال کردم sni رو اشتباه تولید میکنه و از پنل سنایی استفاده میکنم و در اس ان ای uuid رو میزنه و در ادامه خوده دامنه اصلی رو میندازه به عنوان مثال در sni
 d4e316d3-69b8-42a5-8-68244c1f2682.example.com
نوع کد جنریت شده از ربات 
vless://d4e316d3-69b8-42a5-8-68244c1f2682@yourdomain.com:443?type=tcp&security=reality&fp=randomized&pbk=lgD2ztC6UxaI8feoBEop81mlAdyB8twvlURBLRNkTx8&sni=d4e316d3-69b8-42a5-8-68244c1f2682.yourdomain.com&sid=9ea9812b&spx=/https://www.varzesh3.ir/news#Pingless-UAE-459341602-94157
اگر جایی رو اشتباه رفتم لطفا بفرمایید
ما بقی پنل اوکی و بدونه مشکله
تشکر فروان

**Comment by wizwizdev** [comment]
سلام اشتباه نیست، رهگذر خودش اینطوری گفته باید رندم تولید کنه

**Comment by wizwizdev** [comment]
و رهگذر هم فقط vless و vmess داره که شرایطش فرق داره و ریلتی براش چیزی من تعریف نکردم

**Comment by yazdaniyan73** [comment]
آیا این امکان هست این تست درست شه یا نه 
جسارتا یه باگ دیگه هم هست که در ریلیتی جنیرت شده قسمت flow=xtls-rprx-vision رو فعال نمیکنه و به طبع سکیوریتی کسی که مثل ما به صورت مستقیم استفاده میکنه میاره پایین امکان رفع شدن این قضعیه هست یا ما هم تانل کنیم ؟

**Comment by yazdaniyan73** [comment]
> > آیا این امکان هست این تست درست شه یا نه ؟
> > جسارتا یه باگ دیگه هم هست که در ریلیتی جنیرت شده قسمت flow=xtls-rprx-vision رو فعال نمیکنه و به طبع سکیوریتی کسی که مثل ما به صورت مستقیم استفاده میکنه میاره پایین امکان رفع شدن این قضعیه هست ؟
> 
> فک نکنم اضافه بشه معلوم نیست اصلا
> 
> مورد بعدی باگ داشت باگش رفع شد اگه اپدیت نکردین حتما اپدیت کنین و سوالات متداول هم نوشتم چجوری انجام بدین که براتون فعالش کنه

**Comment by yazdaniyan73** [comment]
جسارتا لینک سوالات متداول لطف میکنین بدین
