### ISSUE TITLE
تعداد روز باقیمانده

### ISSUE THREAD

**Issue by sinaf2000** [wizwizdev/wizwizxui-timebot#4]
عدم نمایش تعداد روز باقیمانده در دکمه شیشه ای نمایش کانفیگ
///همه دکمه ها سالمه حتی نمایش تاریخ ولی دکمه تعداد روز باقیمانده نمایش داده نمیشه

**Comment by wizwizdev** [comment]
سلام لطف کنید به نسخه 5.0.2 اپدیت کنید و اگر از نسخه های سنایی و علیرضا ورژن اخر استفاده میکنید نوع پنل رو توی ربات روی سنایی - علیرضا انتخاب کنید مشکل برطرف میشه

**Comment by sinaf2000** [comment]
آپدیت کردم سرور هارو دوباره اضافه کردم پنل هم ساده هس انتخاب کردم اما بازم تعداد روز باقیمانده نشون نمیده

**Comment by wizwizdev** [comment]
اگه اپدیت کردین باید پنل رو سنایی انتخاب کننی نه ساده

**Comment by sinaf2000** [comment]
![image](https://user-images.githubusercontent.com/29178747/227716189-813377b7-4c00-4ead-814b-762b3d36d72a.png)
بفرما لطفا مشکل رو حل کن ممنون

**Comment by wizwizdev** [comment]
شما اپدیت نکردین ، لطف کنین اخرین نسخه رو اپدیت کنین یا از اول پروژه رو دانلود و نصب کنین
