### ISSUE TITLE
ارسال نکردن کانفیگ در ربات

### ISSUE THREAD

**Issue by ayoub510800** [wizwizdev/wizwizxui-timebot#41]
سلام با پنل چینی کار میکنم از امروز صبح کانفیگ رو در پنل میسازه اما در ربات ارسال نمیکنه ولی وقتی به قسمت کانفیگ های من میرم اونجا 
هستش
نسخه پنل هم 1.7.5 هست

**Comment by ali90500** [comment]
منم دقیقا همین مشکل برام پیش اومد

**Comment by wizwizdev** [comment]
> سلام با پنل چینی کار میکنم از امروز صبح کانفیگ رو در پنل میسازه اما در ربات ارسال نمیکنه ولی وقتی به قسمت کانفیگ های من میرم اونجا هستش نسخه پنل هم 1.7.5 هست

تو کانال اطلاعیه قرار گرفت

**Comment by wizwizdev** [comment]
> منم دقیقا همین مشکل برام پیش اومد

تو کانال اطلاعیه قرار گرفت
