### ISSUE TITLE
مشکل در اضافه کردن سرور 

### ISSUE THREAD

**Issue by Hesam-TG** [wizwizdev/wizwizxui-timebot#42]
من یه سرور داشتم و اد کرده بودم تو بات الان دقیقن یه سرور کپی اون زدم و اون مشکل اطلاعات اشتباه  هست میده لطفا لینکای گیت هابو و تلگرامو نزار کاملا بلدم  و میدونم باید چکار کنم همرو صد بار چک کردمو و انجام دادم چکار کنم؟

**Comment by Hesam-TG** [comment]
با دامنه هست ssl داره و مشابه سرور قبلم درستش کردم که به راحتی چند بار دیگه هم اونو اد زدم

**Comment by Hesam-TG** [comment]
پورتم هم 8080 زدم هم 443

**Comment by wizwizdev** [comment]
پس مشکل از هاستته یا سرورت یکی از اینا
