### ISSUE TITLE
مشکل در فعال سازی ربات

### ISSUE THREAD

**Issue by hazhan4268** [wizwizdev/wizwizxui-timebot#45]
سلام وقت بخیر من توکن ربات رو دروست میزنم اما باز میگه اشتباه هستش حتی چند باری توکن ربات رو تغییر دادم

**Comment by wizwizdev** [comment]
سلام

اگه تو هاست نصب کردین این دوتارو تو اکستنش فعال کنید
allow_url_fopen
fileinfo.enable_cli

اگه تو سرور نصب کردین این مراحل رو برید البته اگه توکن رو درست میزنید

برید این مسیر
/etc/php/7.4/apache2/php.ini

این دوتا فایل و پیدا کن
allow_url_fopen = Off
fileinfo.enable_cli = Off
و دوتاشم چنج بده به
allow_url_fopen = On
fileinfo.enable_cli = On
