### ISSUE TITLE
نحوه بکاپ گرفتن و اجرای اون تو سرور جدید بات

### ISSUE THREAD

**Issue by Elyarojaghi** [wizwizdev/wizwizxui-timebot#461]

**Comment by ItsAmirAT** [comment]
بکاپ فقط یه فایل دینابیس ک توی دیتابیس ربات جدید ایمپورت میکنی.

**Comment by mobohes** [comment]
> بکاپ فقط یه فایل دینابیس ک توی دیتابیس ربات جدید ایمپورت میکنی.

ممکنه توضیح بدید چطوری؟
