### ISSUE TITLE
باگ زیرمجموعه گیری⚠️

### ISSUE THREAD

**Issue by mostafajafari00** [wizwizdev/wizwizxui-timebot#469]
وقتی کاربری برای اولین بار توسط دوستش معرفی میشه باید اعتبار هدیه دریافت کنه

قرار نیست با هر خرید اعتبار هدیه بگیره اینجوری امتیاز دعوت از دوستان بی‌معنی میشه

مثل برنامه بلوبانک با هر دعوت فقط یک بار ۳۵ تومن هدیه میده برای هر تراکنش بانکی که مدام اعتبار نمیده!!!

این رو درست کنید چون اگر پیشنهاد خرید رو مبلغی پایین بزاریم که بصرفه برای ما باشه برای کاربر جذابیت نداره اگر هم بالا بزاریم کلی اعتبار هست که شارژ میشه براشون و برای ما بصرفه نیست

**Comment by mostafajafari00** [comment]
الان تست کردیم با خرید اول باید اعتبار بده که میده

برای خرید های بعدی هم مدام هدیه میده در صورتی که باید شرط بزاریم اگر خرید اولی هست فقط هدیه ارسال بشه

**Comment by wizwizdev** [comment]
این باگ نیست و روالش همینه موفق باشید
