### ISSUE TITLE
مشکل افزودن سرور

### ISSUE THREAD

**Issue by topmizban** [wizwizdev/wizwizxui-timebot#48]
سلام من پنل هام مستقیم هستن
یکیشون هدر داره یکیشون نداره
لطفا راهنمایی کنید چطوری اضافه کنم چون هر طوری اضافه میکنم اخرش میگه اشتباه کردی
چندین روزه درگیرشم لطفا راهنماییم کنید

**Comment by topmizban** [comment]
سلام نمیشه منو راهنمایی کنید ؟ با انواع پورت تست کردم
با سه مدل پنل تست کردم
الان پنل چینی ساده دارم هر جوری هم میزنم ( اطلاعاتی که وارد کردی اشتباهه 😂 ) پیغام میده
لطفا راهنمایی بفرمایید ممنون میشم

**Comment by wizwizdev** [comment]
سلام
تنظیمات سرور تو گیت رو بخونید کامل توضیح داده شده

**Comment by topmizban** [comment]
سلام مشکل بنده حل شد
مشکل بخاطر بسته بودن پورت بود که با باز کردنش حل شد
