### ISSUE TITLE
مشکل در تمدید سرویس 

### ISSUE THREAD

**Issue by MAhdioypu** [wizwizdev/wizwizxui-timebot#491]
سلام و درود خسته نباشید 
یک مشکلی در تمدید سرویس هست که ربات حجم کاربر رو ریسیت نمیکنه فقط تایم جدید به سرویس میده این مشکل از سمت ما هست یا باگ رباته آخرین نسخه پنل صنایی نصب هست و ابونتو 20 برای ویز ویز

**Comment by wizwizdev** [comment]
سلام وقت بخیر
سمت پنل شماست
چون اوکی هست مشکلی نداره

**Comment by amirng** [comment]
سلام منم مشکل مشابهی دارم
حجم رو مثلا میکنه ۱۰ گیگ ولی ریست نمیکنه حجم کل رو
کانفیگی هم که میسازه میاد دوبار عدد میزنه
مثلا میزنه
test-test-65876
اینطوری
باید چیکارش کنیم؟

**Comment by MAhdioypu** [comment]
پنلی که خودتون گفتید نصب هست 
دقیقعا باید چیکارش کنم لطفا راهنمایی کنید

**Comment by MAhdioypu** [comment]
دستی که میخوایم این ارور رو میده Error: Request failed with status code 404

**Comment by MAhdioypu** [comment]
مشکل از پنل بود تشکر
