### ISSUE TITLE
مشکل توکن ربات

### ISSUE THREAD

**Issue by topmizban** [wizwizdev/wizwizxui-timebot#50]
سلام
بیشتر از 30 بار توکن ساختم و ربات ساختم اما هر بار پیغام توکن اشتباه است رو میده
واقعا نمیدونم چه کنم ؟

**Comment by wizwizdev** [comment]
سلام

اگه تو هاست نصب کردین این دوتارو تو اکستنش فعال کنید
allow_url_fopen
fileinfo.enable_cli

اگه تو سرور نصب کردین این مراحل رو برید البته اگه توکن رو درست میزنید

برید این مسیر
/etc/php/7.4/apache2/php.ini

این دوتا فایل و پیدا کن
allow_url_fopen = Off
fileinfo.enable_cli = Off
و دوتاشم چنج بده به
allow_url_fopen = On
fileinfo.enable_cli = On

**Comment by topmizban** [comment]
ممنون از پاسختون
خیلی عجیبه جفتش روشنه ، توکن هم درسته اما بازم اون پیغام رو میده !

**Comment by topmizban** [comment]
اتفاقا همین کارو میکنم روی یک هاست دیگ هم بردم ولی بازم این اتفاق میوفته
اینطور که مشخصه از توکن هست ولی نمیدونم چشه واقعا

**Comment by topmizban** [comment]
5 تا ربات ساختم با 5 تاش هم این ارور رو میده

**Comment by wizwizdev** [comment]
مشکلی نداره نمیدونم هرچی هست از طرف شماست و مشکلاتی که اینطوری میشه هم گفتم پس از اینم نباشه دیگه حتماشما اشتباه وارد میکنید

**Comment by topmizban** [comment]
الان ببینید
https://api.telegram.org/bot5668341271:AAFBP45Cb5L9O1Ad1yu-tdkd9lS4xJ2tG2A/getwebhookinfo
این توکن درسته و داره true برمیگرده اما وقتی داخل ربات میذارم میگه توکن وجود ندارد

**Comment by wizwizdev** [comment]
توکن رو اینجا نفرستید سواستفاده میشه
به هرحال شما درست پیش نمیرین 
مشکلات احتمالی رو گفتم خدمت شما فقط همیناست
دیگه نمیدونم
