### ISSUE TITLE
مشکل در request header

### ISSUE THREAD

**Issue by AmirAAAL** [wizwizdev/wizwizxui-timebot#51]
سلام
پنل چینی رو به ربات متصل کردم و request_header و رو تنظیم کردم به عنوان مثال test.com
هنگامی که کانفیگ رو می سازه ربات test.com ادخل request header توی پنل روی کانفیگ مورد نظر هست
اما
کلید اتصالی که میده به کاربر داخل اون نیست! و کلید اتصالی که ربات میده با کلید اتصالی که داخل پنل هست فرق داره! اما با اینکه کلید رو خود ربات ساخته!

**Comment by wizwizdev** [comment]
سلام همیشه اینطوریه یا بعضی اوقات؟

**Comment by AmirAAAL** [comment]
همیشه

**Comment by AmirAAAL** [comment]
و حتی request header کار نمیکنه؛ داخل دیتابیس هست ولی request header رو قرار نمیده روی کانفیگ.
من رفتم داخل config.php لاین 1062 - 1063 رو ویرایش کردم تا قرار بده روی کانفیگ!
![apa](https://user-images.githubusercontent.com/64137693/236192826-740f54f3-829e-4e7d-addb-312dd5b7e157.png)

**Comment by wizwizdev** [comment]
شما اصلا بلدیدی چطوری request header کار کنید که میگید نداره ؟
برید گیت رو بخونید تو قسمت نکته های مهم نوشته شده
برای استفاده از HTTP و Header در ربات باید مقدار Header Type رو مقدار http قرار بدید و برای request header هم مقدار Host:domain.ir وارد کنید

**Comment by AmirAAAL** [comment]
بله، الان تغییر دادم درست شد، راسما سورس رو خراب کرده بودم 😅☹️
ممنون بابت راهنمایی
