### ISSUE TITLE
خطا در امکانات ربات

### ISSUE THREAD

**Issue by shin4128** [wizwizdev/wizwizxui-timebot#526]
اول از همه سلام و تشکر از زحماتت که اینقدر قوی و خوب کار کردی
چندتا مشکل بنظرم اومد که خواستم اعلام کنم تا شاید به بهتر شدنش کمک کنه
+اول اینکه زمانی که برای ربات ادمین تعیین میکنی هیچ پیامی براش ارسال نمیشه وعملا کارایی نداره( میشه به ربات ادمین اضافه کرد و...)
+زیرمجموعه گیری رو نمیشه حذف کرد
+لیست اعضا رو نمیشه مشاهده و ادیت کرد فقط نماینده ها قابل دیدن و ادیت هست
+پلن ها رو اگه میشد در نمایش گروه بندی کرد خیلی شکیل تر میشد
+دریافت شماره تلفنن کار نمیکنه و دوباره درخواست میکنه
+در ساخت انبوه بعد از انتخاب پلن مورد نظر دوباره باید حجم و روز وارد کرد که دلیلشو نمیدونم
+ازداخل وب پنل روی بعضی از پنل ها نمیتوان مستقیم پلن و دسته ساخت و باید حتما از ربات اولین کانفیگ را ساخت و کپی و تغییر داد از وب پنل

**Comment by wizwizdev** [comment]
سلام وقت بخیر
شما ی بار ویزویز رو حذف کنید مجدد نصب کنید
