### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by masih1998** [wizwizdev/wizwizxui-timebot#532]
سلام وقت بخیر
من خواستم آخرین بخش خرید که کانفیگ رو تحویل میده فارسی کنم و سابسکریپشن لینک رو بردارم و اما لینک وضعیت اکانت به صورت وب بمونه

**Comment by Mahdibr77** [comment]
سلام وقت بخر میگم اخرین اپدیتو که انجام دادم اخرین پنل سنایی و پنل ویز ویزو رباتش الان پنل سنایی به ارور برمیخوره چرا؟

**Comment by masih1998** [comment]
سلام ممنون
ربات ویز ویز با یک نسخه از پنل سنایی بدون مشکل
دستور نصب اون نسخه رو این زیر واست نوشتم:
bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v1.7.9

**Comment by Mahdibr77** [comment]
نصب کردم همینو نصب شد ولی به ارور میخوره کانفیگ ها وصل نمیشن

**Comment by Mahdibr77** [comment]
با ورژن 1.7.8 مشکل ندارم ولی وقتی آپدیتش میکنم x.ray ارور میده
