### ISSUE TITLE
مشکل اضافه شدن سرور

### ISSUE THREAD

**Issue by Yanbvr** [wizwizdev/wizwizxui-timebot#54]
وقتی که سرورمو اضافه میکنم میگه در حال ورود به اکانت
تبریک سرور رو ثبت کردی و با موفقیت ذخیره شد
ولی وقتی وضعیت سرور ها رو میزنم میگه هنوز هیچ سروری رو اضافه نکردی! اصلاً کلا هیچ سروری اضافه نشده واسم!
پنلم ورژن ساده نیکودا پورت پنلم ۲۰۵۳ مشکل از کجاست ؟!

**Comment by wizwizdev** [comment]
سلام
وضعیت سرور فقط مربوط به کانفیگ های اشراتکی هست یعنی شما اگه یه پورتی دارید  و چند یوزر از اون پورت استفاده میکنند فقط ظرفیت اون رو میگه برای همین

**Comment by Yanbvr** [comment]
> سلام وضعیت سرور فقط مربوط به کانفیگ های اشراتکی هست یعنی شما اگه یه پورتی دارید و چند یوزر از اون پورت استفاده میکنند فقط ظرفیت اون رو میگه برای همین

خب من از کجا بفهمم که سرورم ثبت شده؟ و بعد از ثبت سرور باید چه مراحلی رو طی کنم؟ یه نکته دیگه وقتی که خرید اکانت رو میزنم میگه فعلا هیچ سرور فعالی نداریم! آیا این واسه این هستش که هنوز پلان ها رو انتخاب نکردم یا بخاطر متصل نشدن به سرورم هستش؟ سپاس از پاسخگویی و زحمات زیادی که میکشی ❤️

**Comment by wizwizdev** [comment]
بعد از ثبت سرور باید گزینه ( افزودن دسته ) بزنید یک دسته ایجاد کنید ، بعدش گزینه ( افزودن پلن) رو بزنید و پن ایجاد کنید و بعد خرید کنید وگرنه بدون دسته و پلن نمیشه خریدی انجام داد

**Comment by Yanbvr** [comment]
> بعد از ثبت سرور باید گزینه ( افزودن دسته ) بزنید یک دسته ایجاد کنید ، بعدش گزینه ( افزودن پلن) رو بزنید و پن ایجاد کنید و بعد خرید کنید وگرنه بدون دسته و پلن نمیشه خریدی انجام داد

من الان مدیریت سرور ها رو که میزنم میگه هنوز هیچ یروری ثبت نکردی! در حالی که قبلا چندینبار امتحان کرده بودم و گفت در حال ورود به اکانت و مشخصات ذخیره شد این یه موضوع، موضوع بعدی  اینه که وقتی میخوام پلان ها رو واسه بار اول ثبت کنم میگه یه دسته جدید انتخاب کن که میکنم بعد میگه لطفاً یکی از سرور ها رو انتخاب کن، و بعد اسم و لیست هیچ یروری رو نشون نمیده! فقط اسم دسته هارو نشون میده که وقتی میزنم روشون اتفاقی نمی‌افته! 
اینم بگم که از سرور استفاده میکنم سرور رو هم همین الان آپدیت کردم، و ورژن یرور هم اوبونتو ۲۰ هستش. چیکار باید کنم؟🤦

**Comment by wizwizdev** [comment]
به زودی برای این موارد آموزش اوکی میشه صبر کنید تا اماده بشه

**Comment by Yanbvr** [comment]
> به زودی برای این موارد آموزش اوکی میشه صبر کنید تا اماده بشه

پس منتظریم مرسی❤️❤️❤️
