### ISSUE TITLE
مشکل در آپدیت با اسکریپت

### ISSUE THREAD

**Issue by karimiorg** [wizwizdev/wizwizxui-timebot#55]
هنگام انجام مراحل ابتدایی آپدیت با خطای ایمیل رو به رو میشم
![image](https://user-images.githubusercontent.com/132637250/236375118-92930c62-5bd6-41b7-8e79-033869a173d9.jpeg)

**Comment by wizwizdev** [comment]
مجدد تست کنید یکم پیش برطرف شد
