### ISSUE TITLE
مراحل خرید

### ISSUE THREAD

**Issue by topmizban** [wizwizdev/wizwizxui-timebot#56]
سلام روزتون بخیر
آیا میشه مراحل خرید رو تغییر داد ؟ الان اول سرور بعدش دسته بندی بعدش پلان انتخاب میشه و خرید انجام میشه
آیا میشه کاری کرد بعد از انتخاب سرور ، پلان انتخاب کنه و خرید انجام بشه
این وسط دسته بندی هارو حذف کرد

**Comment by wizwizdev** [comment]
سلام ممنون
خیر متاسفانه نمیشه
