### ISSUE TITLE
ادمین عزیز زیرمجموعه گیری خراب است لطفا کسانی که این مشکل را دارن توی این پست اعلام کنند

### ISSUE THREAD

**Issue by mohsens00067** [wizwizdev/wizwizxui-timebot#561]
سلام
من یک اکانت جدید تلگرام ساختم
با لینک دعوت عضو شدم
خرید زدم
و بعد چک کردم
هیچ پولی به اکانت معرف اضافه نشد
این اکانت جدید قبلا به هیچ عنوان عضو ربات نشده بود و جدید ساختمش 
لطفا زیر مجموعه گیری را درست کنید
ممنون بابت زحماتتون

دوستان همدرد لطفا اعلام کنند

**Comment by wizwizdev** [comment]
سلام الان تست شد مشکلی نداره
حتما عضو بوده قبلا
شما با چ روشی خرید کردین؟

**Comment by wizwizdev** [comment]
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/27927279/f1b58e46-b4cf-48c1-983f-612898e95362)

**Comment by AloMyVPN** [comment]
![Screenshot_20231031_004948_Telegram](https://github.com/wizwizdev/wizwizxui-timebot/assets/147165319/bec5a8c8-2c40-4a60-8dfb-48560f91fe9f)

**Comment by AloMyVPN** [comment]
تنظیمات LINK رو توی ربات و پنل پیدا نکردم. لینکی هم ایجاد نمی‌کنه.

**Comment by mohsens00067** [comment]
> سلام الان تست شد مشکلی نداره حتما عضو بوده قبلا شما با چ روشی خرید کردین؟

سلام
آره تست شد کار میکنه
اکانتی که لینکم رو داده بودم
ادمین بوده
واسه همین کار نکرده
پس اکانت اگه ادمین باشه کار نمیکنه

**Comment by mohsens00067** [comment]
> تنظیمات LINK رو توی ربات و پنل پیدا نکردم. لینکی هم ایجاد نمی‌کنه.

دوست عزیز توی متنتون این کلمه لینک رو باید قرار بدین تا کار کنه

**Comment by AloMyVPN** [comment]
درود، من کلاً ویزویز نسخه ۹.۱ رو نصب کردم، توی پنل داشبوردی جایی برای انجام این کار نیست که LINK رو تایپ کنم، توی تنظیمات مدیریت تلگرامی هم گزینه‌ای نیستش. من دنبال اون گزینه‌ام، هیچ متنی رو هم نمیشه ویرایش کرد.
