### ISSUE TITLE
عدم نمایش تمامی کاربران در پنل ویز ویز

### ISSUE THREAD

**Issue by mehdi7arfand10** [wizwizdev/wizwizxui-timebot#573]
![IMG_20231031_161914](https://github.com/wizwizdev/wizwizxui-timebot/assets/132158452/d9be0ba0-e654-4978-804f-a472cbce364d)
من امروز پنل رو آپدیت کردم و به این مشکل بر خوردم.. 
فقط ۱۰ تا از کاربرام رو توی لیست بهم نشون میده..
هم روی سیستم هم روی گوشی تست کردم..
سرور رو ریبوت کردم..
تنظیمات پنل ویز ویز هم قسمت اولش برام پاک شده ( قسمتی که تایید شماره و چیزای دیگ بود )

**Comment by wizwizdev** [comment]
مجدد پنل رو اپدیت کنید حل شده

**Comment by mehdi7arfand10** [comment]
متاسفانه بعد از آپدیت کردن دوباره هم مشکل حل نشد.. میشه دوباره به نسخه ی ۸.۲.۲ برگردوند پنل رو؟

**Comment by mehdi7arfand10** [comment]
نسخه ی ۸.۲.۲ کامل و بدون مشکل برام کار میکرد
