### ISSUE TITLE
دلیل نا پدید شدن خودکار کانفینگ ها

### ISSUE THREAD

**Issue by mehdi7arfand10** [wizwizdev/wizwizxui-timebot#579]
کانفینگ ها نا پدید میشن از توی پنل x-ui دلیلش چیه؟
فقط نا پدید میشن، ینی نمیشه از روی پنل x-ui بهشون دسترسی داشت دیگه ولی کانفینگ کار میکنه.. خیلی عجیبه.
من 5روزه دارم از پنل ویز ویز استفاده میکنم و دو دفعه برام این مشکل پیش اومد هم ورژن 8.2.2 هم 9.1.1 چون از قبل بکاپ داشتم از پنلم، با اون تونستم دوباره کانفینگ ها  رو برگردونم

**Comment by mehdi7arfand10** [comment]
نکته هایی درمورد کامل شدن این موضوع بگم،
توی مشکلات دیدم که یه نفر درمورد بروزرسانی لینک میگفت که ممکنه مشکل بخاطره این موضوع باشه.. سری اول که این اتفاق افتاد رو نمیدونم که بروزرسانی لینک روشن بود یا نه ولی سری دوم که روی نسخه 9.1.1 بود این قابلیت رو روشن گذاشته بودم..
کانفینگ های مشتریهامو بطور دستی توی پنل ویز ویز اضافه کردم تا بتونن از قسمت کانفینگ های من به سرویساشون دسترسی داشته باشن...
و روی سرور هام فقط ریلیتی مستقیم دارم

**Comment by mehdi7arfand10** [comment]
واقعا رباتتون عالیه ولی این مشکل خیلی مشکل بزرگیه برای همین مجبور شدم بات رو خاموش کنم تا به راه حلی از طرف شما برسم برای حلش..
ممنون بابت زحماتی که میکشین🙏

**Comment by wizwizdev** [comment]
سلام خیر همچین مشکلی وجود نداره
و هرچی هست مربوط به پنل شماست که باگ خورده باید ی پنل جدید بالا بیارید

**Comment by mehdi7arfand10** [comment]
ممنون از اینکه جواب دادین..
از پنل بکاپ گرفتم و بردم روی یه پنل و سرور جدید دیگه ولی بازم کامل کل کاربرا رو نشون نداد بهم..
کانفینگا پاک نشدن بصورت کامل چون کار میکردن، فقط از روی پنل نمیشد بهش دسترسی داشت
