### ISSUE TITLE
باگ شدید امنیتی

### ISSUE THREAD

**Issue by arshyabahoosh78** [wizwizdev/wizwizxui-timebot#58]
![Screenshot_۲۰۲۳-۰۵-۰۵-۲۱-۱۱-۰۳-۷۴۵_org telegram messenger](https://user-images.githubusercontent.com/132699853/236528430-927cb33f-9781-45ed-b05e-9f9c654f666a.jpg)
![Screenshot_۲۰۲۳-۰۵-۰۵-۲۱-۱۰-۵۸-۶۴۰_org telegram messenger](https://user-images.githubusercontent.com/132699853/236528447-b50ffa4c-c279-449c-94ca-6315b03407ac.jpg)
ربات خیای راحت هک میشه الان سه بار رباتو زدن

**Comment by ezizfazel** [comment]
حاجی کص ننت الان بیا هک کن چونی🖕🏿

**Comment by wizwizdev** [comment]
اپدیت کنید ربات رو صبح اپدیت اومده مشکلی پیش نمیاد
