### ISSUE TITLE
اپدیت  ربات

### ISSUE THREAD

**Issue by ali8080** [wizwizdev/wizwizxui-timebot#59]
سلام 
اگر ربات رو اپدیت کنم بخش هایی که گفتید رو جاگزین کنیم 

توی بخش کانفیگ من بخش تمدید به مشکل نمیخوره ؟
چون هربار اپدیت میدید نمیشه دیگه از اون استفاده کرد

**Comment by wizwizdev** [comment]
سلام واضح تر بگید بخش کانفیگ من چه ربطی به اپدیت داره؟

**Comment by ali8080** [comment]
ببینید هر کانفیگ که فروش میره 
توی بخش کانفیگ های من میاد بعد که روش ضربه میزنی مشخصات میاد 

حالا هروقت که اپدیت میکنیم ربات رو 
این بخش کانفیگ های من پقتی روی کانفگی ضربه میژنیم کار نمیکنه 
میخاستم ببینم این اپدیت اخرم همینجوری میشه یا ن

**Comment by wizwizdev** [comment]
نه ربطی نداره همچین چیزی وجود نداره شما حتما دستکاری میکنید اینطوری میشه، ولی باید حتما اپدیت کنید ، نکنید به ضرر خودتونه

**Comment by wizwizdev** [comment]
باگ برطرف شد میتونید مجدد دستور اپدیت رو بزنید
