### ISSUE TITLE
آپدیت ربات

### ISSUE THREAD

**Issue by hazhan4268** [wizwizdev/wizwizxui-timebot#60]
سلام وقت بخیر از وقتی که ربات رو آپدیت کردم
تو قسمت تنظیمات ربات به مشکل خوردم میخواهم کارت به کارت رو غیر فعال کنم ولی غیر فعال نمیشه کلا هر دکه ای میزنی میای بیرون باز میری هیچ تغییری نکرده

**Comment by hazhan4268** [comment]
حتی کانال درآمدم ست میکنم میام بیرون باز اونم رفته

**Comment by wizwizdev** [comment]
سلام بعد اپدیت اینطوری شده یا قبلنم مشکل داشتید؟ و اخرین بار طبق اطلاعیه کانال اپدیت کردین؟

**Comment by hazhan4268** [comment]
> سلام بعد اپدیت اینطوری شده یا قبلنم مشکل داشتید؟ و اخرین بار طبق اطلاعیه کانال اپدیت کردین؟

خیر قبلا مشکل نداشت تو چنل گفتید آپدیت کنید منم آپدیت کردم

**Comment by hazhan4268** [comment]
> سلام بعد اپدیت اینطوری شده یا قبلنم مشکل داشتید؟ و اخرین بار طبق اطلاعیه کانال اپدیت کردین؟

 [New Recording - ۱۴۰۲/۲/۱۶, ۱۲:۲۲:۴۲](https://vimeo.com/824313920/323e4d6a8c)

**Comment by wizwizdev** [comment]
اون مشکل تنظیمات رو باید بررسی کنم اگر باگ باشه سریع رفع میشه
برای لینک نرمز افزار هم وقتی شما روی سرور نصب میکنید به شما یدونه لینک نصب میده و یدونه لینک phpmyadmin که میتونید با وارد شدن به اون لینک به دیتابیس wizwiz وارد بشید و جدول مربوط به needed_sofwares که مال لینک هست ویرایش کنید

**Comment by wizwizdev** [comment]
برا رفع تنظیمات میتونید یه کاری رو انجام بدید چون یه مشکلی تو ساختارش پیش اومده به زودی رفع میشه 
ولی اگه میخاید زودتر رفع کنید کافیه تو پوشه settings یه فایل به اسم botstate.json رو پاک کنید و همین رو دوباره اپلود کنید رفع میشه
برا اینکار نرم افزار winscip یا termius نصب کن که دسترسی به فایل داشته باشی
یا از طریق سایت shellngn برو
وقتی رفتی وارد این مسیر شو
/var/www/html/wizwizxui-timebot/settings

**Comment by hazhan4268** [comment]
> برا رفع تنظیمات میتونید یه کاری رو انجام بدید چون یه مشکلی تو ساختارش پیش اومده به زودی رفع میشه ولی اگه میخاید زودتر رفع کنید کافیه تو پوشه settings یه فایل به اسم botstate.json رو پاک کنید و همین رو دوباره اپلود کنید رفع میشه برا اینکار نرم افزار winscip یا termius نصب کن که دسترسی به فایل داشته باشی یا از طریق سایت shellngn برو وقتی رفتی وارد این مسیر شو /var/www/html/wizwizxui-timebot/settings

این کارم کردم بازم نشد

**Comment by wizwizdev** [comment]
باگ برطرف شد میتونید مجدد دستور اپدیت رو بزنید
