### ISSUE TITLE
مشکل درگاه ترون

### ISSUE THREAD

**Issue by S8-Ram** [wizwizdev/wizwizxui-timebot#602]
سلام
مشکل من به این صورت هست که آدرس کیف پول ترون رو داخل بات اضافه میکنم و درگاه ترون رو هم فعال میکنم کاربر موقع خرید وقتی درگاه ترون رو انتخاب میکنه هیچی براش ارسال نمیشه درواقع ربات مدت کوتاهی هنگ میکنه. دستور /start رو وقتی میزنم منوی اصلی نمایش داده میشه ولی هیچکدوم از دکمه ها کار نمیکنه وقتی روی دکمه میزنی همیونطوری میمونه بعد از چند دقیقه که ربات از هنگ درمیاد جواب میفرسته
مشکل از کجا میتونه باشه؟ فایل لاگی داخل سرور ‌ذخیره میشه تا بررسی کنم کجا به ارور میخوره؟

**Comment by m-mahmoudi** [comment]
این مشکل بالا واسه منم هست
کسی راهکاری داره؟

**Comment by moandes** [comment]
مشکلتون حل شد؟ 
من هنوز تو اپدیت جدید هم درگاه ترون برام کار نمیکنه!
