### ISSUE TITLE
لینک نرم افزار ها

### ISSUE THREAD

**Issue by hazhan4268** [wizwizdev/wizwizxui-timebot#61]
ببخشید من ربات رو تو سرور ران کردم چطور می تونم لینک نرم افزار هارو تغییر بدم؟

**Comment by wizwizdev** [comment]
سلام تو قسمت phpmyadmin باید برید اونجا میتونید جدول مربوط به لینک هاررو ببینید

**Comment by hazhan4268** [comment]
> سلام تو قسمت phpmyadmin باید برید اونجا میتونید جدول مربوط به لینک هاررو ببینید

خب من از سرور استفادە میکنم

**Comment by hazhan4268** [comment]
بعد اینکە نکجا بتونم متن استارت رو عوض کنم؟

**Comment by wizwizdev** [comment]
داخل فایل bot

**Comment by hazhan4268** [comment]
> داخل فایل bot

خب من از سرور استفاده میکم فایل bot از کجا بیارم

**Comment by wizwizdev** [comment]
نرم افزار winscip یا termius نصب کن که دسترسی به فایل داشته باشی
یا از طریق سایت shellngn برو
وقتی رفتی وارد این مسیر شو
/var/www/html/wizwizxui-timebot
 و هر فایلی خواستی ادیت بزن
