### ISSUE TITLE
ارسال چند کانفیگ پشت سرهم بعد از تایید 

### ISSUE THREAD

**Issue by mrhooshmandtech** [wizwizdev/wizwizxui-timebot#612]
سلام وقتتون بخیر
بعد از تایید چند تا کانفیگ ساخته میشه و ارسال میشه 
مشکل از چیه بنظرتون؟

**Comment by AliHemmati79** [comment]
سلام
احتمالا تو قسمت تنظیمات سرور بخش ip از چند نوع ساب دامین استفاده کردین.

**Comment by mramir-pc** [comment]
نه یک دامنه فقط قرار داده شده
