### ISSUE TITLE
مشکل در خاموش کردن درگاه پرداخت

### ISSUE THREAD

**Issue by karimiorg** [wizwizdev/wizwizxui-timebot#62]
بعد از آپدیت (توسط اسکریپت) در قسمت تنظیمات ربات مشکل به وجود آمده است.

هنگام خاموش کردن هر یک از بخش ها
بخش دیگری روشن می‌شود و بعد از بازگشت مجدد همه روشن هستند. در تعریف کانال ارسال گزارش خرید هم همین مشکل وجود دارد

![image](https://user-images.githubusercontent.com/132637250/236621325-2b67b86c-e586-4fca-ab1b-d4bef0233a02.jpeg)

**Comment by wizwizdev** [comment]
برا رفعش میتونید یه کاری رو انجام بدید چون یه مشکلی تو ساختارش پیش اومده به زودی رفع میشه 
ولی اگه میخاید زودتر رفع کنید کافیه تو پوشه settings یه فایل به اسم botstate.json رو پاک کنید و همین رو دوباره اپلود کنید رفع میشه
برا اینکار نرم افزار winscip یا termius نصب کن که دسترسی به فایل داشته باشی
یا از طریق سایت shellngn برو
وقتی رفتی وارد این مسیر شو
/var/www/html/wizwizxui-timebot/settings

**Comment by karimiorg** [comment]
فایل botstate.json رو از مسیری که گفتید پاک و مجدد در همون مسیر آپلود کنم؟

**Comment by karimiorg** [comment]
کلا اون فایل رو پاک کردم و الان درست شده
مجدد که آپلودش می‌کنم دوباره مشکل پیدا میکنه

**Comment by wizwizdev** [comment]
خب شما کلا پاک کنید که فایل نباشه به درد نمیخوره
مشکل داره گفتم این مدلی برطرف کنید ولی انگاری جوابگو نبوده ، به زودی برطرف میشه
برطرف شد همینجا اعلام میکنم

**Comment by karimiorg** [comment]
وقتی پاک می‌کنم دکمه خرید کانفیگ و چند نا دکمه دیگه ناپدید میشه

**Comment by hazhan4268** [comment]
> وقتی پاک می‌کنم دکمه خرید کانفیگ و چند نا دکمه دیگه ناپدید میشه

من کدم ادیت کردم ولی بعد میگه متاسفانه فعلا فروش نداریم

**Comment by wizwizdev** [comment]
باگ برطرف شد میتونید مجدد دستور اپدیت رو بزنید

**Comment by hazhan4268** [comment]
> باگ برطرف شد میتونید مجدد دستور اپدیت رو بزنید

الان وقتی یکی از تیک هارو غیر فعال می کنی کلا دیگه نمی تونی کانفیگ بگیری میگه فعلا فروش نداریم

**Comment by hazhan4268** [comment]
> باگ برطرف شد میتونید مجدد دستور اپدیت رو بزنید

![image](https://user-images.githubusercontent.com/132519868/236642578-ccc8d567-cba5-4d5c-b313-dbc00df22413.png)
فروشم فعاله ولی این جوری میگە

**Comment by wizwizdev** [comment]
یک بار تنظیمات ربات رو خاموش روشن کنید درست میشه

**Comment by hazhan4268** [comment]
> یک بار تنظیمات ربات رو خاموش روشن کنید درست میشه

کردم نشد

**Comment by wizwizdev** [comment]
مجدد اپدیت کنید حتما درست اپدیت نکردین
