### ISSUE TITLE
ویزویز بیچاره ام کردی 92 ترابات دانلود کردی واسه چی اخه؟؟؟

### ISSUE THREAD

**Issue by itbaz2010** [wizwizdev/wizwizxui-timebot#627]
![image](https://github.com/wizwizdev/wizwizxui-timebot/assets/141946219/1089bffb-b6ba-4ed9-ac0b-0a0d01923614)
73 یورو رفت تو پاچه ام 
خدا ازت نگذره ویزویز 
92 ترابایت دانلود چی داشتی اخه لامصب؟
اخرین نسخه هم هستم

**Comment by wizwizdev** [comment]
عقل که نباشید جان در عذاب است ( چنگیز )

همین الانم ایپیت لو رفت

**Comment by itbaz2010** [comment]
خاموشش کردم سرور رو 
ای پی هم پاکش میکنم بره 
من با این فیلترینگ دارم هر 2-3 روز یکبار ای پی عوض میکنم نگران ای پی نباش
برو ببین باگ پنلت کجاست که با سرور من اینهمه دانلود کردن

**Comment by uzer98** [comment]
باگ Sql injection داره 😅
