### ISSUE TITLE
باگ مهم : مشکل استارت بات روی هاست

### ISSUE THREAD

**Issue by diakolabra** [wizwizdev/wizwizxui-timebot#636]
من ربات رو روی هاست پیاده کردم اما یه باگه اساسی داره و اونم اینه که کابر باید دوبار دستور start رو بفرسته تا ربات فعال بشه و اکثره کابرا فک میکنن  بات کار نمیکنه و هی پیام میدن یا اینکه منصرف میشن از خرید
اولش فکر کردم مشکل از سمته هاسته تا اینکه هاستمو تغییر دادم اما دیدم همچنان این مشکل هستش 
لطفا این باگ رو فیکس کنید

**Comment by wizwizdev** [comment]
ربات روی هاست کار نمیکنه و دیگ همچین سوالی نپرسید

**Comment by MarKi44** [comment]
ورژن php رو به 8.1 تغییر بدید درست میشه
