### ISSUE TITLE
درگاه پرداخت

### ISSUE THREAD

**Issue by hazhan4268** [wizwizdev/wizwizxui-timebot#64]
ببخشید ایا با ویرایش کد ها امکان داره قابلیت پرداخت با درگاه پرداخت آقای پرداخت اضافه کرد؟ خودم بلد نیستم اگه شما خودتان ادیت کنید برام چقد هزینه می برە؟

**Comment by hazhan4268** [comment]
الان من زرین پال دارم برای ٦٠٠٠٠ تومان از مشتری ١٥٠٠ تومان کارمزد میگیری
بهشونم که میگم میگن چون سایت نداری همینه کە هست علی دارە دزدی میکنە تازە خیلی هم دیر تسویه میزنه ولی آقای پرداخت با تسویه دستیش ٢ ساعته تو حسابتە

**Comment by wizwizdev** [comment]
سلام نه متفاوت از هم هستن و فرق میکنه

**Comment by hazhan4268** [comment]
> سلام نه متفاوت از هم هستن و فرق میکنه
خب نمیشه یه جور کد نویسی کرد براش؟

**Comment by wizwizdev** [comment]
میشه

**Comment by hazhan4268** [comment]
خب چقد هزینه می برە؟

**Comment by hazhan4268** [comment]
> میشه

من خودم بلد نیستم اگه شما برام ادیت کنید چقد میگیرید؟

**Comment by hazhan4268** [comment]
هعی

**Comment by wizwizdev** [comment]
> 

ادیت که نمیشه باید اضاف بشه دوست عزیز وقت میبره اینا
