### ISSUE TITLE
درگاه nowpayment

### ISSUE THREAD

**Issue by karimiorg** [wizwizdev/wizwizxui-timebot#66]
درود، درگاه nowpayment رو در فایل بیس اینفو اضافه میکنم اما داخل ربات به نمایش در نمیاد، در صورت امکان بفرمایید چطور فعال میشه تشکر.

هم لینک تست کردم هم api خالی
هیچکدوم فعال نشد

**Comment by wizwizdev** [comment]
سلام دوست عزیز
 درگاه nowpayment فقط برای کیف پول هست اپدیت بعدی برای بخش های دیگه هم اضافه میشه
