### ISSUE TITLE
مشکل sni 

### ISSUE THREAD

**Issue by msv9** [wizwizdev/wizwizxui-timebot#661]
سلام وقت بخیر
من vless grpc tls دارم
خب توی قسمت sni باید ادرس دامنه پنل رو وارد کنم
وقتی توی ربات یا توی سرور ادرس sni رو میزنم توی کانفیگ خروجی sni خالی میوفته
راه حلی براش نیست؟
پ.ن: ادرس sni و ادرس پنل یکیه

**Comment by karim20012** [comment]
منم این مشکل رو دارم

**Comment by msv9** [comment]
> منم این مشکل رو دارم
من به جای grpc از ws  استفاده کردم حل شد
ولی خب روی grpc همچنان مشکل هست

**Comment by wizwizdev** [comment]
سلام وقتم خالی نیست هرموقع وقت کنم بررسی میکنم

**Comment by msv9** [comment]
نمیدونم چطور‌ ولی حلش کردم ممنون

**Comment by ServerNitro** [comment]
منم این مشکل رو دارم چجوری حلش کردی؟
