### ISSUE TITLE
مشکل SQL Injection در Wizwiz

### ISSUE THREAD

**Issue by uzer98** [wizwizdev/wizwizxui-timebot#662]
با توجه به نگرانی‌های امنیتی درخصوص اسکریپت WizWiz؛ توصیه میکنم تا زمانی‌که آسیب‌پذیری‌‌هایی مثل SQL Injection درش دیده‌میشه، ازش استفاده نکنید!
برای زحمات تیم توسعه‌دهنده‌ش احترام قائلم، اما کدهای پروژه به بازنگری نیاز داره.

👉 https://x.com/ircfspace/status/1727658943260893687

**Comment by wizwizdev** [comment]
چشماتو باز کن این و بخون
https://t.me/wizwizch/445

**Comment by uzer98** [comment]
شما چشماتو‌‌ باز کن
اولا توئیت مربوط به ۵ روز پیش هست که گفته مشکل همچنان وجود داره
دوما گفته مشکل SQL Injection که بخاطر ضعف اصول اولیه برنامه نویسی هست و چه ربطی به https://t.me/wizwizch/445 داره
