### ISSUE TITLE
مشکل در گرفتن ssl

### ISSUE THREAD

**Issue by ArtinTomcat** [wizwizdev/wizwizxui-timebot#67]
سلام من وقتی اسکریپت رو ران کردم بخش فعالسازی ssl سریع رد شد میشه دستور حذف ربات رو بگین تا دیلیت کنم و دوباره نصبش کنم.

**Comment by wizwizdev** [comment]
سلام مشکلی نداره مجدد دستور نصب رو بزنید اگر ssl نزدین
