### ISSUE TITLE
حمایت

### ISSUE THREAD

**Issue by ali8080** [wizwizdev/wizwizxui-timebot#7]
ویز ویز جان مرسی از این نسخه و نسخه های جدیدی که قراره بدی 
خسته نباشی عزیز

**Comment by wizwizdev** [comment]
قربون شما

**Comment by zimxghr** [comment]
سوتون به پنل 3x-ui روی پروتکل tcp باید چطوری وصل کنم ؟ هر کاری میکنم نمیشه .
سوتون کنکور رو چی کار میکنی چقدر خوندی ؟ آریان رو ساب داشتی تل از اینجا میگم :/

**Comment by HamidRouter** [comment]
وقت بخیر ویزویز جان واقعا پروژه بی نظیری داری و لایق بهترین ها هستی دستت طلا منتظر نسخه جدید و بی نظیرت هستیم

**Comment by wizwizdev** [comment]
> 

اگه اشتراکی منظورته باید اول کانفیگ بزنی و بقیش رو به بات بسپاری و بات رو روی حالت اشتراکی بزاری

**Comment by wizwizdev** [comment]
> سوتون به پنل 3x-ui روی پروتکل tcp باید چطوری وصل کنم ؟ هر کاری میکنم نمیشه . سوتون کنکور رو چی کار میکنی چقدر خوندی ؟ آریان رو ساب داشتی تل از اینجا میگم :/


اگه اشتراکی منظورته باید اول کانفیگ بزنی و بقیش رو به بات بسپاری و بات رو روی حالت اشتراکی بزاری

**Comment by wizwizdev** [comment]
> وقت بخیر ویزویز جان واقعا پروژه بی نظیری داری و لایق بهترین ها هستی دستت طلا منتظر نسخه جدید و بی نظیرت هستیم

ممنونم از شما
