### ISSUE TITLE
نحوه حذف نصب بات از لینوکس

### ISSUE THREAD

**Issue by zir4k** [wizwizdev/wizwizxui-timebot#70]
با سلام و وقت بخیر
طفا نحوه حذف کامل ربات و موارد نصبی در پکیج سیستم عامل اوبونتو رو اعلام کنید با تشکر.

**Comment by HosseinB00** [comment]
> 

انجام دادم ولی این دو تا پیام برام میاد، چکار کنم؟

![photo_2023-06-06_13-27-28](https://github.com/wizwizdev/wizwizxui-timebot/assets/135634848/e773c561-7e62-4a48-b9f6-cc365d7af44d)
![photo_2023-06-06_13-27-39](https://github.com/wizwizdev/wizwizxui-timebot/assets/135634848/bde72db5-d6e2-4f5d-90bc-bb037c97fdb6)
