### ISSUE TITLE
مشکل ارسال پیام همگانی

### ISSUE THREAD

**Issue by amirng** [wizwizdev/wizwizxui-timebot#72]
سلام من از نسخه هاست دارم استفاده میکنم بعد از اینکه اپدیت کردم نمیتونم پیام همگانی بفرستم باید چیکار کنم ممکن هست توضیح بدید یا چطوری دانگرید کنم به ورژن قبلی

**Comment by wizwizdev** [comment]
سلام
ادرس کرون جاب تغییر کرده باید طبق اون پیش برید ببینید که فایل کرون جاب کجاست تنظیمش کنید چون پوشه بندی تغییر کرده

**Comment by amirng** [comment]
سلام خیلی ممنون
