### ISSUE TITLE
بارها گفته شده ولی  اهمیت ندادید

### ISSUE THREAD

**Issue by MrTrc** [wizwizdev/wizwizxui-timebot#720]
کسی از داخل ربات خریداری نکرده و کانفیگش دستی زده شده موقع تموم شدن کانفیگش اصلا متوجه نمیشه ! 
و هیچ پیامی بهش نمیره 
فقط باید خودش دستی بیاد چک کنه ببینه حجمش تموم شده یا نه 
فقط برا کسایی پیام میره که از خوده ربات خریداری کردن و این اوکی نیست اصلا

**Comment by wizwizdev** [comment]
همینطوری بوده و همینطوری خواهد بود و تغییری نمیکنه

**Comment by MrTrc** [comment]
> همینطوری بوده و همینطوری خواهد بود و تغییری نمیکنه

اشتراکی پس به درد من نمیخوره چون فروش من حجمیه ، و نیاز دارم مشتریم بفهمه وقتی میخواد حجمش تموم بشه ، نه اینکه از ربات خریداری بشه ، از ورژن 2 به بعد برداشتی این آپشن خرابش کردی ،
