### ISSUE TITLE
باگ ربات در ثبت سرور جدید در قسمت tls

### ISSUE THREAD

**Issue by mohamadrezaeimail** [wizwizdev/wizwizxui-timebot#739]
سلام 
بعد از اپدیت جدید ربات، یک باگ پیش اومده که وقتی سرور جدید در ربات ثبت میکنی ،ثبت میشه،  ولی وقتی اشتراک میسازی با سرور جدیدی که ثبت شده ،لینکی که ربات تحویل میده قسمت tls   خالی هست ,و در پنل هم تب  Inbounds باگ میخوره و خالی نشون میده،در واقع کانفیگی که در پنل میسازه قسمت "streamSettings"  خالی میمونه ,ربات اطلاعات اشتباه در دیتابیس در tlsSettings  ثبت میکنه!!!
حالا اگر سروری که ثبت کردی رو بری توی پنل ویزویز، قسمت سرور ادیت بزنی و بدون تغییری ذخیره بزنی مشکل حل میشه و باگ رفع میشه

این مشکل بعد از اپدیت ربات ایجاد شده
![bug](https://github.com/wizwizdev/wizwizxui-timebot/assets/117741202/b35215a2-9af7-4975-8789-20d2ae20dde6)

**Comment by wizwizdev** [comment]
😕
