### ISSUE TITLE
طرح صفحه payment

### ISSUE THREAD

**Issue by irpicsi** [wizwizdev/wizwizxui-timebot#749]
این طرح رو برای صفحه پرداخت زدم 
خوبه؟
[pay.zip](https://github.com/wizwizdev/wizwizxui-timebot/files/13805073/pay.zip)

**Comment by wizwizdev** [comment]
قشنگه ولی برای کجا طراحی کردین؟

**Comment by irpicsi** [comment]
برای pay.php و index.php دایرکتوری pay
