### ISSUE TITLE
باگ‌های موجود

### ISSUE THREAD

**Issue by irpicsi** [wizwizdev/wizwizxui-timebot#758]
#باگ

۱- عدم کارکرد کد تخفیف ۱۰۰ درصدی
۲- عدم نمایش تعداد خرید و میزان درآمد نماینده در پنل نماینده و ادمین
۳- عدم کارکرد صحیح تخفیف برای تمدید کانفیگ در پنل نماینده
۴- عدم نمایش صحیح کانفیگ در تیکت

#پیشنهاد

- حذف پنل و قراردادن آن در نسخه اشتراکی

**Comment by wizwizdev** [comment]
اینا باگ نیستن 
شماره 1 مشکل نداره
شماره 2 فقط ادمین میتونه ببینه
شماره 3 فقط خرید هست نه تمدید
شماره 4 مشکل نداره
هرچی هست از دستکاری شماست یا مشکل دیگس

حذف پنل نوشتین هم خود ربات داره

**Comment by irpicsi** [comment]
شماره سه برای تمدید هم بود اما بعد از آپدیت حذف شد!
نمیدونم چرا حذفش کردی...

**Comment by irpicsi** [comment]
![photo_2024-01-06_13-27-19](https://github.com/wizwizdev/wizwizxui-timebot/assets/135636752/d20a9817-f449-4449-a2b5-2d2f78d84898)
![photo_2024-01-06_13-27-26](https://github.com/wizwizdev/wizwizxui-timebot/assets/135636752/fe95aac3-a49f-4913-b7aa-1f811191a387)
![photo_2024-01-06_13-27-32](https://github.com/wizwizdev/wizwizxui-timebot/assets/135636752/f38946ab-658b-4c0b-9206-09725fe44b20)

این تصاویر مربوط به نسخه ۸ هست که بکاپش رو داشتم...
هم تعداد خرید نماینده رو میزنه و هم نماینده میتونه تمدید کنه اما توی آخرین نسخه هم تعداد خرید رو ۰ میزنه و هم نماینده نمیتونه تمدید کنه!
