### ISSUE TITLE
ارور 443 در هنگام ورود به پنل ویزویز

### ISSUE THREAD

**Issue by parsa-ui** [wizwizdev/wizwizxui-timebot#759]
سلام
وقت بخیر
بعد از ایجاد رکورد جدید در cloudflare و ساخت database ویزویز، وقتی که آدرس پنل رو بهم میده و اون رو سرچ می کنم، با خطای 443 روبرو میشم، ممنون میشم کمک کنین.
![wizwiz error](https://github.com/wizwizdev/wizwizxui-timebot/assets/108423138/fb8fe49a-1050-42b8-a4c7-5b82ca59b2cc)

**Comment by wizwizdev** [comment]
سلام مشکل از دامنه شماست یا اینکه درست نصب نشده اموزش توی کاناله
