### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by ahwazi12** [wizwizdev/wizwizxui-timebot#77]
سلام  سر پنل چینی   شبکه  از حالت wsیاtcpو...عوض نميشه

**Comment by wizwizdev** [comment]
سلام نسخه درست که گفتم نصب کنید

**Comment by ahwazi12** [comment]
اخرین نسخه  رو هاست اپلود کردم

**Comment by wizwizdev** [comment]
خب از پنل دیگه استفاده کنید چون روی چینی بیشتر مانور نداده شده و ورژن هم دقت کنید ننوشتیم ، حتما رفع میکنیم
