### ISSUE TITLE
صفحه سفید بعد از لاگین

### ISSUE THREAD

**Issue by oooookeyyyyy** [wizwizdev/wizwizxui-timebot#773]
سلام بعد از نصب صفحه لاگین میاد ولی وقتی وارد میشی صفحه سفیده

**Comment by oooookeyyyyy** [comment]
دیتابیس wizwiz خالیه فکر میکنم مشکل همین باشه، یا اشتباه میکنم؟ یوزر پس پنل رو از کجا میخونه؟

**Comment by dadashali61** [comment]
منم همین مشکل رو دارم. چطوری میشه حلش کرد؟
