### ISSUE TITLE
باگ تو دیتابیس

### ISSUE THREAD

**Issue by ezizfazel** [wizwizdev/wizwizxui-timebot#79]
سلام بعد چند روز استفاده از ربات دیتابیس پنلم باگ خورده ، دِو عزیز لطفا راهنمایی فرمایید جهت حل مشکل 
![CE5D0BFF-9A66-4A96-8CAA-4B4279BA4021](https://github.com/wizwizdev/wizwizxui-timebot/assets/67505036/d04c9d13-4bc6-4ed1-b40e-26dd13707f02)

**Comment by wizwizdev** [comment]
سلام نسخه ای که گفتم و استفاده نکردی برای همین
تو. گیت نوشتم راه حل رو بخونید
