### ISSUE TITLE
عدم کارکرد ربات

### ISSUE THREAD

**Issue by alisorena1993** [wizwizdev/wizwizxui-timebot#806]
در داخل ربات پیام های بروزرسانی و بکاپ دیتابیس از سرور میاد ولی وقتی داخل تلگرام /start میزنم هیچ کاری نمیکنه

**Comment by alisorena1993** [comment]
مشکل حل شد از تنظیمات دسترسی کلادفلر بود. باید ساب دامنه ربات رو اکسکلود میکردم

**Comment by SirBahador** [comment]
> مشکل حل شد از تنظیمات دسترسی کلادفلر بود. باید ساب دامنه ربات رو اکسکلود میکردم

میشه بیشتر توضیح بدی چیکار کردی؟
