### ISSUE TITLE
مدیریت پلن ها

### ISSUE THREAD

**Issue by alirezafeo** [wizwizdev/wizwizxui-timebot#808]
سلام و ارادت .. ممنون از تیم خفنتون.
من به یه مشکلی برخوردم زمانی که مدیریت پلن هارو میزنم (یا از سمت مشتری خرید کانفیگ جدید) پلن هایی میاد که به اشتباه وارد کردم ولی دکمه ای برای حذف و ویرایش اونها نیست.. ممنون میشم راهنماییم کنید.. راهی هست که ربات ریست بشه و از اول کار تنظیمات پنل رو انجام بدم؟
![photo_2024-01-30_21-09-01](https://github.com/wizwizdev/wizwizxui-timebot/assets/158206200/70be05fb-12f8-49f2-9d64-c8f0e2a6ea2a)
![photo_2024-01-30_21-14-27](https://github.com/wizwizdev/wizwizxui-timebot/assets/158206200/652a567d-76f1-42c4-8005-5db0d8fd4f35)

**Comment by wizwizdev** [comment]
سلام برید توی مدیریت ربات - مدیریت پلن ها و روی سرور مورد نظر کلیک کنید پلن هارو میاره و میتونید پاک کنید ، یا هم برید توی پنل ویزویز و از اونجا پلن هارو پاک کنید
