### ISSUE TITLE
از کار افتادن ربات

### ISSUE THREAD

**Issue by alisorena1993** [wizwizdev/wizwizxui-timebot#810]
بعد از چند ساعت ربات از کار میوفته مشکل از چی میتونه باشه؟

**Comment by wizwizdev** [comment]
از هاست یا سرورت

**Comment by alisorena1993** [comment]
مشکل حل شد از تنظیمات دسترسی کلادفلر بود. باید ساب دامنه ربات رو اکسکلود میکردم

> از هاست یا سرورت

**Comment by Hossein52Hz** [comment]
> مشکل حل شد از تنظیمات دسترسی کلادفلر بود. باید ساب دامنه ربات رو اکسکلود میکردم
> 
> > از هاست یا سرورت

سلام وقت بخیر
میشه راهنمایی کنید از کدوم قسمت باید این کار را انجام داد؟
سابدامنه ربات همون سابدامنه پنل wizwiz هست که موقع نصب بهش میدیم؟
مرسی
