### ISSUE TITLE
مشکل در تکرر ارسال کانفیگ

### ISSUE THREAD

**Issue by arian2240** [wizwizdev/wizwizxui-timebot#83]
سلام خسته نباشید هنگامی که فیش کارت به کارت کسی را برای درخواست کانفیگ قبول میکنیم پس از قبول فیش اگر دستمان روی دکمه تیک بخورد کانفیگ مجددا ارسال میشود.

**Comment by arian2240** [comment]
و لطفا در اخرین مرحله یعنی مرحله ارسال فیش دکمه برگشت به مرحله قبل برداشته شود و فقط دکمه منصرف شدم باقی بماند چون با زدن دکمه برگشت به مرحله قبل در قسمت ارسال فیش یه پیام تاییدیه پوچ به ادمین ارسال میشود

**Comment by wizwizdev** [comment]
سلام کارت ب کارت خرید کانفیگ مشکلی نداره و دوبار نمیفرسته ، بعد اینکه فرستاده حالتش تیک میخوره و دیگ نمیشه فرستاد
حالا چرا فقط شما این مشکلات رو دارین کسی نمیگه؟ ی جا حتما اشتباه پیش میرین دوست عزیز

**Comment by ezizfazel** [comment]
داش منم اگه چن بار بزنم روش ، چن تا براش میفرسته ، و اینکه هدر رو اکثر مواقع نمیزنه داخل کانفیگ

**Comment by wizwizdev** [comment]
> داش منم اگه چن بار بزنم روش ، چن تا براش میفرسته ، و اینکه هدر رو اکثر مواقع نمیزنه داخل کانفیگ

کارت ب کارت تمدید یا چی؟ چند نوع کارت ب کارت داریم خرید - تمدید شما کدومش مشکل دارین؟
