### ISSUE TITLE
هک شدن ربات

### ISSUE THREAD

**Issue by ErfanAhmadi1378** [wizwizdev/wizwizxui-timebot#842]
سلام دیشب یک تیم هکری ریختن سر رباتم و تقریبا همه چیزو بهم ریخته بودن
لطفا اگر باگی چیزی مونده فیکس کنید

**Comment by wizwizdev** [comment]
سلام ما 3 روز پیش اپدیت دادیم اپدیت کردین؟

**Comment by ErfanAhmadi1378** [comment]
اره اخرین نسخه بود

**Comment by wizwizdev** [comment]
خیر من میدونم نبوده چون رفع شده جز این دسترسی دیگ نداره
