### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by ezizfazel** [wizwizdev/wizwizxui-timebot#86]
جسارت نباشه ولی بنظر بنده اول باگ‌های این ورژن رو کامل رفع کنید بعد به فکر امکانات دیگر باشید ❤️

**Comment by wizwizdev** [comment]
> جسارت نباشه ولی بنظر بنده اول باگ‌های این ورژن رو کامل رفع کنید بعد به فکر امکانات دیگر باشید ❤️

باگ هاش چدتا رفع شده و با اپدیت جدید میاد
