### ISSUE TITLE
قابلیت ادد اجباری

### ISSUE THREAD

**Issue by letmefind** [wizwizdev/wizwizxui-timebot#868]
سلام 

امکان اضافه کردن عضویت اجباری کاربر به پنل هست ؟ 
تلاش کردم که کد رو اضافه کنم اما موفق نشدم به خوبی انجامش بدم .

**Comment by wizwizdev** [comment]
سلام یعنی چی به پنل؟
عضویت اجباری فقط برای کانال هست

**Comment by letmefind** [comment]
اشتباه تایپی بود. بله عضویت اجباری فقط برای کانال . 
من مقدار join_channel_message تو value میبینم اما در قسمت تنظیمات بات یا پنل ایتم **عضویت اجباری** رو پیدا نمیکنم که تنظیم یا تغییر بدم .

**Comment by letmefind** [comment]
این **[راهکار](https://github.com/wizwizdev/wizwizxui-timebot/issues/102)** هم تست کردم اما تو نسخه 7.5.3 ظاهرا کارایی داشته. اما تو نسخه اخیر موفق نشدم عضویت اجباری رو فعال کنم .

**Comment by letmefind** [comment]
مشکل حل شد. تنظیمات در قسمت 'تنظیم درگاه بود'
