### ISSUE TITLE
تغییر متن خوش امدگویی

### ISSUE THREAD

**Issue by pourdarai** [wizwizdev/wizwizxui-timebot#876]
سلام وقت بخیر
متن خوش امدگویی ربات (سلااام به ربات ویزویز خوش اومدی 🫡🌸)رو میخوام تغییر بدم رفتم تو پوشه var بعد www بعد html بعد wizwizxui-timebot بعد فایل bot.php رو ویرایش کردم ولی متن خوش امدگویی نبود
از کجا میتونم پیداش کنم؟
ممنون از زحماتی که میکشین

**Comment by Blaster-777** [comment]
برو تو پوشه settings فایل values رو ویرایش کن
