### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by erfantab** [wizwizdev/wizwizxui-timebot#878]
سلام و خسته نباشید
من امروز خواستم که پنل رو روی سرورم نصب بکنم ولی از وقتی وارد کردم دستور رو فقط داره نتایج عکس دوم رو میده و تموم نمیشه
مشکل چیه؟
![Screenshot (789)](https://github.com/wizwizdev/wizwizxui-timebot/assets/161929095/c91a0d01-41c9-4293-8935-8c36b527b3f2)
![Screenshot (788)](https://github.com/wizwizdev/wizwizxui-timebot/assets/161929095/50094c90-df9d-4e9c-b948-f6fed0681a79)

**Comment by wizwizdev** [comment]
سلام سرور رو یک بار ریبیلد کنین و از اول نصب کنین

**Comment by erfantab** [comment]
> سلام سرور رو یک بار ریبیلد کنین و از اول نصب کنین

**Comment by erfantab** [comment]
> سلام سرور رو یک بار ریبیلد کنین و از اول نصب کنین

ریبیلد کردم ولی دوباره مثل همینه تا ign22اپدیت میشه میره دوباره از اول و بعد چند بار ارور میده
