### ISSUE TITLE
مشكل كمك پليز

### ISSUE THREAD

**Issue by Armingbz** [wizwizdev/wizwizxui-timebot#88]
سلام و خسته نباشيد
بنده هر پنل ميزنم به ربات اضافه ميشه اما به پنل دارم اصلا به ربات اضافه نميشهو ميگه رمز اشتباهه با اينكه رمز و يوزرش درسته

**Comment by wizwizdev** [comment]
سلام گیت و بخونید قسمت تنظیمات ربات

**Comment by Armingbz** [comment]
كدوم قسمت رو بخونم داخل ربات؟

**Comment by Armingbz** [comment]
خوندم ولي من درست وارد ميكنم درست نبود اونيكي هاهم وارد نميشد اونوقت

**Comment by wizwizdev** [comment]
به زودی اموزش اوکی میشه
