### ISSUE TITLE
تانل دکو

### ISSUE THREAD

**Issue by mohamadm0meni** [wizwizdev/wizwizxui-timebot#883]
درود و خسته نباشید به شما 
در تانل دکو باید وقتی در سرور خارج کانفیگ ساخته میشود باید قسمت دامنه رو به دامنه سرور ایران تغییر داد 
آیا میتوان این کار را انجام داد که روی تانل دکو هم کار کنه ؟

**Comment by wizwizdev** [comment]
سلام ربات همه تانل ها کار میکنه فقط باید سروری که ربات روشه با ایران سازگار باشه و ایران اکسس نباشه سرورتون
