### ISSUE TITLE
ارسال پیام همگانی 

### ISSUE THREAD

**Issue by MR-Amoori** [wizwizdev/wizwizxui-timebot#9]
با سلام
در قسمت ارسال پیام همگانی اصلا کار نمیکنه و برای ارسال جدید با این پیام مواجه میشم:

❗️ یک پیام همگانی در صف انتشار می باشد لطفا صبور باشید ...

🔰 تعداد کاربران : 17
☑️ ارسال شده : 0
📣 باقیمانده : 17
⁮⁮ ⁮⁮ ⁮⁮ ⁮⁮
یک روز هم گذشته .

**Comment by MR-Amoori** [comment]
درود

1: 
/usr/bin/php -q /home/kgujvvjg/public_html/https://sh.domian.top/messagewizwiz.php >/dev/null 2>&1

2: 
/usr/bin/php -q /home/kgujvvjg/public_html/https://sh.domin.top/warnUsage.php >/dev/null 2>&1

فایل های پروژه درون Public html هست
این کرون جاب ها هم خود قابلیت نصب آسان ست کرده

**Comment by wizwizdev** [comment]
تو گیت این مدلی نذاشتیم ها با دقت گیت رو چک کن ، بعدشم اسم فایل هم اشتباه دادی گیت اصلا این مدلی نیست
 اینارو کپی کنید و کرونجاب بزارید
/usr/bin/php -q /home/kgujvvjg/public_html/wizwizxui-timebot-main/messagewizwiz.php >/dev/null 2>&1
/usr/bin/php -q /home/kgujvvjg/public_html/wizwizxui-timebot-main/warnusers.php >/dev/null 2>&1
/usr/bin/php -q /home/kgujvvjg/public_html/wizwizxui-timebot-main/rewardReport.php >/dev/null 2>&1

**Comment by MR-Amoori** [comment]
خیلی ممنونم تشکر
