### ISSUE TITLE
عدم اجرا ربات پس از بروزرسانی

### ISSUE THREAD

**Issue by dev-ir** [wizwizdev/wizwizxui-timebot#962]
با سلام 

پس از بروزرسانی به آخرین نسخه ربات ( پنل + بات ) ربات از دسترس خارج شده و دستور استارت عملکرد نشان نمیدهد 

نکته : بک اپ هنوز هر 1 ساعت در حال ارسال به ادمین میباشد اما دستور اجرا با اشکال مواجه میشود 

-- سرویس مرزبان و ... هم اضافه نشده و همانند 1 سال گذشته بر روی xui بوده است --

**Comment by wizwizdev** [comment]
سلام وقت بخیر خیر همچین مشکلی وجود نداره

**Comment by Alij13a** [comment]
> سلام وقت بخیر خیر همچین مشکلی وجود نداره
این مشکل برای منم هست و خیلی وقته که این مشکل وحود داره و حلش نکردید!

**Comment by dev-ir** [comment]
> > سلام وقت بخیر خیر همچین مشکلی وجود نداره
> > این مشکل برای منم هست و خیلی وقته که این مشکل وحود داره و حلش نکردید!

میشه گفت اخر مجبور شدم دانگرید کنم برم اوبونتو 22 یه جا دیگه نصب کنم و بک اپ ریستور کنم به شما هم همین پیشنهاد میکنم
چون نه در لاگ خاصی مشخصه و نه مشکل فعلا برطرف میشه
