### ISSUE TITLE
باگ دریافت پلن مرزبان

### ISSUE THREAD

**Issue by amirhr098** [wizwizdev/wizwizxui-timebot#965]
سلام. اول از همه خیلی ممنون بابت زحماتتون.
من در نسخه جدید ربات پنل مرزبان و پلن مربوط بهش رو هم اضافه کردم و مشکلی نداشت. (لیست اینباندهارو از پنل هم کامل خوند و تونستم انتخاب کنم)
مشکلی که باهاش مواجه شدم این هست وقتی خرید کانفیگ رو میزنم و اون پلن رو انتخاب میکنم، اتفاقی نمی افته. برای چند ثانیه هم ربات هنگ میکنه و هیچ پاسخی نمیده. توی پنل مرزبان هم چیزی ایجاد نمیشه.
ربات رو البته آپدیت کردم از طریق دستوری که گذاشتید، لازم هست حتما دوباره نصب بشه؟ آپدیت پنل و آپدیت ربات باید با ترتیب خاصی انجام بشه؟
قابلیت دیباگی نداره ربات که بشه فعال کرد و دید توی کدوم قسمت گیر میکنه؟

**Comment by wizwizdev** [comment]
سلام وقت بخیر
پلن های مرزبان رو کامل پاک کنید و از اول مجدد اضافه کنید تست کنید خبر بدید

**Comment by amirhr098** [comment]
> سلام وقت بخیر پلن های مرزبان رو کامل پاک کنید و از اول مجدد اضافه کنید تست کنید خبر بدید

سلام. کلا چندبار حذف کردم هم کلا پنل رو و هم پلن های مربوط بهش رو و با تنظیمات مختلف تست کردم. همشون هم حالت رو دارن که وقتی خرید زده میشه ربات هنگ میکنه و چیزی هم ارسال نمیشه، و بعد 2 یا 3 دقیقه دوباره به حالت عادیش برمیگرده.
هر تستی لازم باشه بفرمایید من میگیرم.

**Comment by wizwizdev** [comment]
به این ربات پیام بدید و دسترسی بدید من باگ رو پیدا کنم وگرنه اینطوری نمیتونم بفهمم مشکل چیه چون من سازنده مشکلی ندیدم اگر بفرستین مشکل رو متوجه میشم ، در غیر اینصورت خیر
https://t.me/wizwizbugbot

**Comment by amirhr098** [comment]
ممنون پیام دادم بهتون
