### ISSUE TITLE
پیشنهاد خیلی کاربردی

### ISSUE THREAD

**Issue by ahsvip** [wizwizdev/wizwizxui-timebot#97]
یک دکمه برای دریافت مجدد سشن (همون کوکی) بزنید
این باعث میشه وقتی سرورمون فیلتر شد و ایپیش رو مقلا تو کلودفلر زدیم رو دامنه جدید (بدون پروکسی کلود) ربات مجددا یبار کوکی جدید بگیره پون کوکی معمولا بعد چنج ایپی میسوزه و باید جدیدش رو خودمون دستی بزاریم تو phpmyadmin

این خیلی اذیت کننده است مخصوصا برای بعضی ها که گوشی  دارن و بخوان داخل phpmyadmin ادیت کنن

البته این یک پشنهاد بود و خیلی ام کاربردیه

**Comment by wizwizdev** [comment]
کوکی تو دیتابیس الکی هست شما پاک بکنی هم  سرور روی ربات کار میکنه مشکلی نیست و مهم رمز و نام کاربری
