### ISSUE TITLE
Connection failed: Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by mortazamman** [wizwizdev/wizwizxui-timebot#981]
بعد از نصب ویز ویز آدرس ورود به پنل رو میزنم با این خطا مواجه میشم
Connection failed: Access denied for user ''@'localhost' (using password: NO)

**Comment by wizwizdev** [comment]
با دستور نصب سرور نصب کنید همچین مشکلی پیش نمیاد
