### ISSUE TITLE
اطلاعات خرید و کانفیگ مرزبان

### ISSUE THREAD

**Issue by amirhr098** [wizwizdev/wizwizxui-timebot#983]
سلام وقتتون بخیر.
من برای ارسال پیام های دوره ای به کاربرها، از دیتابیس ویزویز استفاده میکنم و خریدهارو قبلا از تیبل orders_list میخوندم. الان مثل اینکه خریدهای مرزبان توش نمیاد دیگه.
این اتفاق مشکلی از سمت من هست یا توی کد پیاده سازی نشده؟

**Comment by wizwizdev** [comment]
درود
هستش همونجا و ثبت میشه و هستش تا ثبت نشه ک پرداختی کلا انجام نمیشه

**Comment by amirhr098** [comment]
توی تیبل `pays` پرداخت ها میاد، ولی داخل تیبل `orders_list` اطلاعات کانفیگ ها نمیاد. خیلی هم گشتم و با تایم خرید و server_id فیلتر کردم ولی هیچ اطلاعاتی از کانفیگ های مرزبان نیست توش.

**Comment by besttrove** [comment]
خرید های پلن مرزبان تو سفارشات پنل هم نمیاد

**Comment by amirhr098** [comment]
@wizwizdev 
میشه یه چک بکیند که توی دیتابیس مینویسه یا نه؟
من کد رو چک کردم، بعد از اینکه کانفیگ رو ساخت و به کاربر داده اون دستور insert توی orders_list هست. احتمالا اجرا نمیشه به خاطر Null بودن یکی از مقادیرش مثلا protcol که Null میشه برای مرزبان.

**Comment by wizwizdev** [comment]
برطرف شد با اپدیت جدید
